var DualGunner = {
   skillDescription: ["Corrosive Round", "Poison Ivy", "Quicksilver", "Hot Shot", "Stealth", "Full Auto", "Foxglove", "Maelstrom", "Tiger Eye", "Sirocco", "Black Rose", "Hemlock", "Crossfire",
       "Concussive Shock", "Flashbang", "Belladonna", "Reload", "Heartbreaker", "Nightshade", "Elude", "Bloody Rose", "Exploit Weakness", "Misdirection", "Lead Rain", "Death Mark", "Assassinate",
       "Chain Reaction", "Cover Fire", "Breakthrough", "Gunblaze Festival", "Wicked Timer"
   ],
   skillInfo: [
       ["Deals 11 physical damage on impact and an additional 57 damage after 3 seconds",
           "Deals 14 physical damage on impact and an additional 69 damage after 3 seconds",
           "Deals 19 physical damage on impact and an additional 92 damage after 3 seconds",
           "Deals 24 physical damage on impact and an additional 120 damage after 3 seconds",
           "Deals 30 physical damage on impact and an additional 150 damage after 3 seconds",
           "Deals 37 physical damage on impact and an additional 186 damage after 3 seconds",
           "Deals 45 physical damage on impact and an additional 225 damage after 3 seconds",
           "Deals 54 physical damage on impact and an additional 272 damage after 3 seconds",
           "Deals 66 physical damage on impact and an additional 332 damage after 3 seconds",
           "Deals 80 physical damage on impact and an additional 401 damage after 3 seconds",
           "Deals 97 physical damage on impact and an additional 484 damage after 3 seconds",
           "Deals 114 physical damage on impact and an additional 570 damage after 3 seconds",
           "Deals 135 physical damage on impact and an additional 673 damage after 3 seconds",
           "Deals 156 physical damage on impact and an additional 782 damage after 3 seconds",
           "Deals 181 physical damage on impact and an additional 906 damage after 3 seconds",
           "Deals 208 physical damage on impact and an additional 1040 damage after 3 seconds"
       ],
       ["Creates venomous ivy under enemy's feet to immobilize it for 3 seconds. For the duration, this inflicts 33 physical damage per sec and decreases abnormal states RES by 6.",
           "Creates venomous ivy under enemy's feet to immobilize it for 3 seconds. For the duration, this inflicts 44 physical damage per sec and decreases abnormal states RES by 7.",
           "Creates venomous ivy under enemy's feet to immobilize it for 3 seconds. For the duration, this inflicts 58 physical damage per sec and decreases abnormal states RES by 8.",
           "Creates venomous ivy under enemy's feet to immobilize it for 3 seconds. For the duration, this inflicts 72 physical damage per sec and decreases abnormal states RES by 9.",
           "Creates venomous ivy under enemy's feet to immobilize it for 4 seconds. For the duration, this inflicts 89 physical damage per sec and decreases abnormal states RES by 10.",
           "Creates venomous ivy under enemy's feet to immobilize it for 4 seconds. For the duration, this inflicts 108 physical damage per sec and decreases abnormal states RES by 11.",
           "Creates venomous ivy under enemy's feet to immobilize it for 4 seconds. For the duration, this inflicts 131 physical damage per sec and decreases abnormal states RES by 12.",
           "Creates venomous ivy under enemy's feet to immobilize it for 4 seconds. For the duration, this inflicts 160 physical damage per sec and decreases abnormal states RES by 13.",
           "Creates venomous ivy under enemy's feet to immobilize it for 5 seconds. For the duration, this inflicts 193 physical damage per sec and decreases abnormal states RES by 14.",
           "Creates venomous ivy under enemy's feet to immobilize it for 5 seconds. For the duration, this inflicts 233 physical damage per sec and decreases abnormal states RES by 15.",
           "Creates venomous ivy under enemy's feet to immobilize it for 5 seconds. For the duration, this inflicts 275 physical damage per sec and decreases abnormal states RES by 16.",
           "Creates venomous ivy under enemy's feet to immobilize it for 5 seconds. For the duration, this inflicts 324 physical damage per sec and decreases abnormal states RES by 17.",
           "Creates venomous ivy under enemy's feet to immobilize it for 6 seconds. For the duration, this inflicts 376 physical damage per sec and decreases abnormal states RES by 18.",
           "Creates venomous ivy under enemy's feet to immobilize it for 6 seconds. For the duration, this inflicts 436 physical damage per sec and decreases abnormal states RES by 19.",
           "Creates venomous ivy under enemy's feet to immobilize it for 6 seconds. For the duration, this inflicts 498 physical damage per sec and decreases abnormal states RES by 20.",
           "Creates venomous ivy under enemy's feet to immobilize it for 6 seconds. For the duration, this inflicts 563 physical damage per sec and decreases abnormal states RES by 21."
       ],
       ["Increases Movement Speed by 10 and Evasion by 14 for 20 seconds.",
           "Increases Movement Speed by 10 and Evasion by 16 for 21 seconds.",
           "Increases Movement Speed by 10 and Evasion by 18 for 22 seconds.",
           "Increases Movement Speed by 10 and Evasion by 20 for 23 seconds.",
           "Increases Movement Speed by 10 and Evasion by 22 for 24 seconds.",
           "Increases Movement Speed by 10 and Evasion by 24 for 25 seconds.",
           "Increases Movement Speed by 10 and Evasion by 26 for 26 seconds.",
           "Increases Movement Speed by 10 and Evasion by 28 for 27 seconds.",
           "Increases Movement Speed by 10 and Evasion by 30 for 28 seconds.",
           "Increases Movement Speed by 10 and Evasion by 33 for 30 seconds. Applies Quick Step to the user and lets it hide shortly."
       ],
       ["By filling dual pistols with magical power, increases physical damage by 10.",
           "By filling dual pistols with magical power, increases physical damage by 13.",
           "By filling dual pistols with magical power, increases physical damage by 16.",
           "By filling dual pistols with magical power, increases physical damage by 19.",
           "By filling dual pistols with magical power, increases physical damage by 22.",
           "By filling dual pistols with magical power, increases physical damage by 27.",
           "By filling dual pistols with magical power, increases physical damage by 32.",
           "By filling dual pistols with magical power, increases physical damage by 38.",
           "By filling dual pistols with magical power, increases physical damage by 44.",
           "By filling dual pistols with magical power, increases physical damage by 51.",
           "By filling dual pistols with magical power, increases physical damage by 59.",
           "By filling dual pistols with magical power, increases physical damage by 68.",
           "By filling dual pistols with magical power, increases physical damage by 78.",
           "By filling dual pistols with magical power, increases physical damage by 88.",
           "By filling dual pistols with magical power, increases physical damage by 99.",
           "By filling dual pistols with magical power, increases physical damage by 116."
       ],
       ["Hides for 30sec to reset threat rate and decreases move speed by 20.",
           "Hides for 33sec to reset threat rate and decreases move speed by 15.",
           "Hides for 36sec to reset threat rate and decreases move speed by 10.",
           "Hides for 39sec to reset threat rate and decreases move speed by 5.",
           "Hides for 42sec to reset threat rate.",
           "Hides for 45sec to reset threat rate and increases move speed by 2.",
           "Hides for 48sec to reset threat rate and increases move speed by 4.",
           "Hides for 51sec to reset threat rate and increases move speed by 6.",
           "Hides for 54sec to reset threat rate and increases move speed by 8.",
           "Hides for 60sec to reset threat rate and increases move speed by 10."
       ],
       ["Rapid-fires pistols causing 174 physical damage.",
           "Rapid-fires pistols causing 217 physical damage.",
           "Rapid-fires pistols causing 268 physical damage.",
           "Rapid-fires pistols causing 325 physical damage.",
           "Rapid-fires pistols causing 393 physical damage.",
           "Rapid-fires pistols causing 479 physical damage.",
           "Rapid-fires pistols causing 579 physical damage.",
           "Rapid-fires pistols causing 698 physical damage.",
           "Rapid-fires pistols causing 824 physical damage.",
           "Rapid-fires pistols causing 972 physical damage.",
           "Rapid-fires pistols causing 1129 physical damage.",
           "Rapid-fires pistols causing 1308 physical damage.",
           "Rapid-fires pistols causing 1496 physical damage.",
           "Rapid-fires pistols causing 1690 physical damage.",
           "Rapid-fires pistols causing 1901 physical damage.",
           "Rapid-fires pistols causing 2138 physical damage."
       ],
       ["Shoots a venomous bullet that decreases Movement Speed by 15 and inflicts 77 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 17 and inflicts 94 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 19 and inflicts 114 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 21 and inflicts 138 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 23 and inflicts 168 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 25 and inflicts 203 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 27 and inflicts 242 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 29 and inflicts 286 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 31 and inflicts 337 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 33 and inflicts 390 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 35 and inflicts 452 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 37 and inflicts 516 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 39 and inflicts 580 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 41 and inflicts 653 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 43 and inflicts 733 physical damage per sec for 8 seconds.",
           "Shoots a venomous bullet that decreases Movement Speed by 45 and inflicts 818 physical damage per sec for 8 seconds."
       ],
       ["Deals 42 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 51 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 61 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 73 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 87 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 105 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 123 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 145 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 168 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 194 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 222 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 252 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 283 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 317 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 355 additional damage for each physical attack. Lasts for 10 seconds.",
           "Deals 394 additional damage for each physical attack. Lasts for 10 seconds."
       ],
       ["Increases critical rate by 1 and critical damage by 3%",
           "Increases critical rate by 2 and critical damage by 6%",
           "Increases critical rate by 3 and critical damage by 9%",
           "Increases critical rate by 4 and critical damage by 12%",
           "Increases critical rate by 5 and critical damage by 15%",
           "Increases critical rate by 6 and critical damage by 18%",
           "Increases critical rate by 7 and critical damage by 21%",
           "Increases critical rate by 8 and critical damage by 24%",
           "Increases critical rate by 9 and critical damage by 27%",
           "Increases critical rate by 10 and critical damage by 30%"
       ],
       ["Increases dodge rate by 3.",
           "Increases dodge rate by 4.",
           "Increases dodge rate by 5.",
           "Increases dodge rate by 6.",
           "Increases dodge rate by 7.",
           "Increases dodge rate by 8.",
           "Increases dodge rate by 9.",
           "Increases dodge rate by 10.",
           "Increases dodge rate by 11.",
           "Increases dodge rate by 12."
       ],
       ["Increases critical rate by 20 for 2 minutes.",
           "Increases critical rate by 23 for 2 minutes.",
           "Increases critical rate by 26 for 2 minutes.",
           "Increases critical rate by 29 for 2 minutes.",
           "Increases critical rate by 32 for 2 minutes.",
           "Increases critical rate by 35 for 2 minutes.",
           "Increases critical rate by 38 for 2 minutes.",
           "Increases critical rate by 41 for 2 minutes.",
           "Increases critical rate by 44 for 2 minutes.",
           "Increases critical rate by 50 for 2 minutes."
       ],
       ["Shoots a venomous bullet that responds to Mana. This inflicts 133 physical damage and takes 8% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 160 physical damage and takes 8% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 194 physical damage and takes 9% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 235 physical damage and takes 9% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 277 physical damage and takes 10% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 328 physical damage and takes 10% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 382 physical damage and takes 11% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 442 physical damage and takes 11% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 506 physical damage and takes 12% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 576 physical damage and takes 12% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 648 physical damage and takes 13% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 728 physical damage and takes 13% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 816 physical damage and takes 14% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 907 physical damage and takes 14% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 1008 physical damage and takes 15% of Max Mana apart and converts into extra damage.",
           "Shoots a venomous bullet that responds to Mana. This inflicts 1120 physical damage and takes 15% of Max Mana apart and converts into extra damage."
       ],
       ["Deals 538 physical damage to enemies within 5 meters.",
           "Deals 650 physical damage to enemies within 5 meters.",
           "Deals 784 physical damage to enemies within 5 meters.",
           "Deals 925 physical damage to enemies within 5 meters.",
           "Deals 1091 physical damage to enemies within 5 meters.",
           "Deals 1267 physical damage to enemies within 5 meters.",
           "Deals 1469 physical damage to enemies within 5 meters.",
           "Deals 1686 physical damage to enemies within 5 meters.",
           "Deals 1898 physical damage to enemies within 5 meters.",
           "Deals 2134 physical damage to enemies within 5 meters.",
           "Deals 2400 physical damage to enemies within 5 meters.",
           "Deals 2682 physical damage to enemies within 5 meters.",
           "Deals 2979 physical damage to enemies within 5 meters.",
           "Deals 3309 physical damage to enemies within 5 meters.",
           "Deals 3677 physical damage to enemies within 5 meters.",
           "Deals 4083 physical damage to enemies within 5 meters."
       ],
       ["Stuns enemy for 10 seconds. Target takes 230 additional damage when attacked. This skill cannot be automatically recast.",
           "Stuns enemy for 12 seconds. Target takes 280 additional damage when attacked. This skill cannot be automatically recast.",
           "Stuns enemy for 14 seconds. Target takes 333 additional damage when attacked. This skill cannot be automatically recast.",
           "Stuns enemy for 16 seconds. Target takes 393 additional damage when attacked. This skill cannot be automatically recast.",
           "Stuns enemy for 18 seconds. Target takes 460 additional damage when attacked. This skill cannot be automatically recast.",
           "Stuns enemy for 20 seconds. Target takes 534 additional damage when attacked. This skill cannot be automatically recast.",
           "Stuns enemy for 22 seconds. Target takes 616 additional damage when attacked. This skill cannot be automatically recast.",
           "Stuns enemy for 24 seconds. Target takes 700 additional damage when attacked. This skill cannot be automatically recast.",
           "Stuns enemy for 26 seconds. Target takes 788 additional damage when attacked. This skill cannot be automatically recast.",
           "Stuns enemy for 30 seconds. Target takes 884 additional damage when attacked. This skill cannot be automatically recast."
       ],
       ["Deals 244 physical damage to all enemies within 3 meters and binds them for 3 seconds.",
           "Deals 294 physical damage to all enemies within 3 meters and binds them for 4 seconds.",
           "Deals 347 physical damage to all enemies within 3 meters and binds them for 5 seconds.",
           "Deals 409 physical damage to all enemies within 3 meters and binds them for 6 seconds.",
           "Deals 475 physical damage to all enemies within 3 meters and binds them for 7 seconds.",
           "Deals 551 physical damage to all enemies within 3 meters and binds them for 8 seconds.",
           "Deals 631 physical damage to all enemies within 3 meters and binds them for 9 seconds.",
           "Deals 712 physical damage to all enemies within 3 meters and binds them for 10 seconds.",
           "Deals 800 physical damage to all enemies within 3 meters and binds them for 11 seconds.",
           "Deals 900 physical damage to all enemies within 3 meters and binds them for 12 seconds."
       ],
       ["Poisons the target to deal damage equivalent to 100% of the recovery when cured. Lasts for 3 cure offects or 10 seconds.",
           "Poisons the target to deal damage equivalent to 110% of the recovery when cured. Lasts for 3 cure offects or 15 seconds.",
           "Poisons the target to deal damage equivalent to 120% of the recovery when cured. Lasts for 3 cure offects or 20 seconds.",
           "Poisons the target to deal damage equivalent to 130% of the recovery when cured. Lasts for 3 cure offects or 25 seconds.",
           "Poisons the target to deal damage equivalent to 140% of the recovery when cured. Lasts for 3 cure offects or 30 seconds.",
           "Poisons the target to deal damage equivalent to 150% of the recovery when cured. Lasts for 3 cure offects or 35 seconds.",
           "Poisons the target to deal damage equivalent to 160% of the recovery when cured. Lasts for 3 cure offects or 40 seconds.",
           "Poisons the target to deal damage equivalent to 170% of the recovery when cured. Lasts for 3 cure offects or 45 seconds.",
           "Poisons the target to deal damage equivalent to 180% of the recovery when cured. Lasts for 3 cure offects or 50 seconds.",
           "Poisons the target to deal damage equivalent to 200% of the recovery when cured. Lasts for 3 cure offects or 60 seconds."
       ],
       ["Resets cooldown time of all skills and decreases all cooldown times by 25% for 30 seconds.",
           "Resets cooldown time of all skills and decreases all cooldown times by 30% for 40 seconds.",
           "Resets cooldown time of all skills and decreases all cooldown times by 35% for 50 seconds.",
           "Resets cooldown time of all skills and decreases all cooldown times by 40% for 60 seconds.",
           "Resets cooldown time of all skills and decreases all cooldown times by 45% for 70 seconds.",
           "Resets cooldown time of all skills and decreases all cooldown times by 50% for 80 seconds.",
           "Resets cooldown time of all skills and decreases all cooldown times by 55% for 90 seconds.",
           "Resets cooldown time of all skills and decreases all cooldown times by 57% for 100 seconds.",
           "Resets cooldown time of all skills and decreases all cooldown times by 59% for 110 seconds.",
           "Resets cooldown time of all skills and decreases all cooldown times by 60% for 120 seconds."
       ],
       ["Inflcits 613 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 723 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 853 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 990 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 1148 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 1313 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 1483 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 1668 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 1875 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 2095 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 2328 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 2585 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 2873 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 3163 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 3480 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second.",
           "Inflcits 3833 physical damage and weakens the enemy's heart for 10 seconds. Every Critical hit stuns an enemy for 3 second."
       ],
       ["Poisoned bullet deals 764 physical damage to the target and paralyzes them for 3 seconds.",
           "Poisoned bullet deals 884 physical damage to the target and paralyzes them for 3 seconds.",
           "Poisoned bullet deals 1012 physical damage to the target and paralyzes them for 3 seconds.",
           "Poisoned bullet deals 1152 physical damage to the target and paralyzes them for 3 seconds.",
           "Poisoned bullet deals 1296 physical damage to the target and paralyzes them for 3 seconds.",
           "Poisoned bullet deals 1456 physical damage to the target and paralyzes them for 3 seconds.",
           "Poisoned bullet deals 1632 physical damage to the target and paralyzes them for 3 seconds.",
           "Poisoned bullet deals 1814 physical damage to the target and paralyzes them for 3 seconds.",
           "Poisoned bullet deals 2016 physical damage to the target and paralyzes them for 3 seconds.",
           "Poisoned bullet deals 2240 physical damage to the target and paralyzes them for 3 seconds."
       ],
       ["Increases resistance to snaring effects by 5% and immobilizing effects by 3%.",
           "Increases resistance to snaring effects by 10% and immobilizing effects by 6%.",
           "Increases resistance to snaring effects by 15% and immobilizing effects by 9%.",
           "Increases resistance to snaring effects by 20% and immobilizing effects by 12%.",
           "Increases resistance to snaring effects by 25% and immobilizing effects by 15%.",
           "Increases resistance to snaring effects by 30% and immobilizing effects by 18%.",
           "Increases resistance to snaring effects by 35% and immobilizing effects by 21%.",
           "Increases resistance to snaring effects by 40% and immobilizing effects by 24%.",
           "Increases resistance to snaring effects by 45% and immobilizing effects by 27%.",
           "Increases resistance to snaring effects by 50% and immobilizing effects by 30%."
       ],
       ["Cast while in Hot Shot(Above Level 1), for 20 seconds, Normal attack deal splash damage equivalent to 20% of Physical ATK, double ATK is increased by 20, and the skill user absorbs 20% of damage on enemies as HP.",
           "Cast while in Hot Shot(Above Level 1), for 22 seconds, Normal attack deal splash damage equivalent to 25% of Physical ATK, double ATK is increased by 22, and the skill user absorbs 25% of damage on enemies as HP.",
           "Cast while in Hot Shot(Above Level 1), for 24 seconds, Normal attack deal splash damage equivalent to 30% of Physical ATK, double ATK is increased by 24, and the skill user absorbs 30% of damage on enemies as HP.",
           "Cast while in Hot Shot(Above Level 1), for 26 seconds, Normal attack deal splash damage equivalent to 35% of Physical ATK, double ATK is increased by 26, and the skill user absorbs 35% of damage on enemies as HP.",
           "Cast while in Hot Shot(Above Level 1), for 28 seconds, Normal attack deal splash damage equivalent to 40% of Physical ATK, double ATK is increased by 28, and the skill user absorbs 40% of damage on enemies as HP.",
           "Cast while in Hot Shot(Above Level 1), for 30 seconds, Normal attack deal splash damage equivalent to 45% of Physical ATK, double ATK is increased by 30, and the skill user absorbs 45% of damage on enemies as HP.",
           "Cast while in Hot Shot(Above Level 1), for 32 seconds, Normal attack deal splash damage equivalent to 50% of Physical ATK, double ATK is increased by 32, and the skill user absorbs 50% of damage on enemies as HP.",
           "Cast while in Hot Shot(Above Level 1), for 34 seconds, Normal attack deal splash damage equivalent to 55% of Physical ATK, double ATK is increased by 34, and the skill user absorbs 55% of damage on enemies as HP.",
           "Cast while in Hot Shot(Above Level 1), for 36 seconds, Normal attack deal splash damage equivalent to 60% of Physical ATK, double ATK is increased by 36, and the skill user absorbs 60% of damage on enemies as HP.",
           "Cast while in Hot Shot(Above Level 1), for 40 seconds, Normal attack deal splash damage equivalent to 70% of Physical ATK, double ATK is increased by 38, and the skill user absorbs 70% of damage on enemies as HP.",
           "Cast while in Hot Shot(Above Level 1), for 40 seconds, Normal attack deal splash damage equivalent to 70% of Physical ATK, double ATK is increased by 40, and the skill user absorbs 70% of damage on enemies as HP."
       ],
       ["Deals 1086 physical damage. 150% damage dealt if the target is stunned.",
           "Deals 1222 physical damage. 152% damage dealt if the target is stunned.",
           "Deals 1376 physical damage. 154% damage dealt if the target is stunned.",
           "Deals 1544 physical damage. 156% damage dealt if the target is stunned.",
           "Deals 1722 physical damage. 158% damage dealt if the target is stunned.",
           "Deals 1912 physical damage. 160% damage dealt if the target is stunned.",
           "Deals 2122 physical damage. 162% damage dealt if the target is stunned.",
           "Deals 2358 physical damage. 164% damage dealt if the target is stunned.",
           "Deals 2618 physical damage. 166% damage dealt if the target is stunned.",
           "Deals 2910 physical damage. 168% damage dealt if the target is stunned.",
           "Deals 3066 physical damage. 170% damage dealt if the target is stunned."
       ],
       ["Decreases threat generated by all attacks and actions and Mana cost of single target skills by 10%. Also, reduces damage from enemies under [Cover Fire] debuff by 75%.",
           "Decreases threat generated by all attacks and actions and Mana cost of single target skills by 12%. Also, reduces damage from enemies under [Cover Fire] debuff by 75%.",
           "Decreases threat generated by all attacks and actions and Mana cost of single target skills by 14%. Also, reduces damage from enemies under [Cover Fire] debuff by 75%.",
           "Decreases threat generated by all attacks and actions and Mana cost of single target skills by 16%. Also, reduces damage from enemies under [Cover Fire] debuff by 75%.",
           "Decreases threat generated by all attacks and actions and Mana cost of single target skills by 18%. Also, reduces damage from enemies under [Cover Fire] debuff by 75%.",
           "Decreases threat generated by all attacks and actions and Mana cost of single target skills by 20%. Also, reduces damage from enemies under [Cover Fire] debuff by 75%.",
           "Decreases threat generated by all attacks and actions and Mana cost of single target skills by 22%. Also, reduces damage from enemies under [Cover Fire] debuff by 75%.",
           "Decreases threat generated by all attacks and actions and Mana cost of single target skills by 24%. Also, reduces damage from enemies under [Cover Fire] debuff by 75%.",
           "Decreases threat generated by all attacks and actions and Mana cost of single target skills by 26%. Also, reduces damage from enemies under [Cover Fire] debuff by 75%.",
           "Decreases threat generated by all attacks and actions and Mana cost of single target skills by 28%. Also, reduces damage from enemies under [Cover Fire] debuff by 75%."
       ],
       ["Deals 2473 physical damage to all enemies within 4 meters of the target.",
           "Deals 2779 physical damage to all enemies within 4 meters of the target.",
           "Deals 3100 physical damage to all enemies within 4 meters of the target.",
           "Deals 3442 physical damage to all enemies within 4 meters of the target.",
           "Deals 3820 physical damage to all enemies within 4 meters of the target.",
           "Deals 4244 physical damage to all enemies within 4 meters of the target.",
           "Deals 4712 physical damage to all enemies within 4 meters of the target.",
           "Deals 5238 physical damage to all enemies within 4 meters of the target.",
           "Deals 5519 physical damage to all enemies within 4 meters of the target."
       ],
       ["Deals 1274 Physical Attack and engraves mark of assasin that all those who attack the target with the mark recovers 202 HP each hit for 10 seconds.",
           "Deals 1428 Physical Attack and engraves mark of assasin that all those who attack the target with the mark recovers 225 HP each hit for 10 seconds.",
           "Deals 1587 Physical Attack and engraves mark of assasin that all those who attack the target with the mark recovers 247 HP each hit for 10 seconds.",
           "Deals 1764 Physical Attack and engraves mark of assasin that all those who attack the target with the mark recovers 271 HP each hit for 10 seconds.",
           "Deals 1960 Physical Attack and engraves mark of assasin that all those who attack the target with the mark recovers 298 HP each hit for 10 seconds.",
           "Deals 2175 Physical Attack and engraves mark of assasin that all those who attack the target with the mark recovers 328 HP each hit for 10 seconds.",
           "Deals 2415 Physical Attack and engraves mark of assasin that all those who attack the target with the mark recovers 360 HP each hit for 10 seconds.",
           "Deals 2683 Physical Attack and engraves mark of assasin that all those who attack the target with the mark recovers 396 HP each hit for 10 seconds."
       ],
       ["Deals 1836 Physical Attack and additional damage, max of 2814, proportinal to HP decrease of the target.",
           "Deals 2041 Physical Attack and additional damage, max of 3092, proportinal to HP decrease of the target.",
           "Deals 2268 Physical Attack and additional damage, max of 3396, proportinal to HP decrease of the target.",
           "Deals 2520 Physical Attack and additional damage, max of 3734, proportinal to HP decrease of the target.",
           "Deals 2797 Physical Attack and additional damage, max of 4100, proportinal to HP decrease of the target.",
           "Deals 3105 Physical Attack and additional damage, max of 4502, proportinal to HP decrease of the target.",
           "Deals 3449 Physical Attack and additional damage, max of 4944, proportinal to HP decrease of the target."
       ],
       ["Deals 2268 Physical Attack and additional 330 damage for each harmful buffs. Enters into chain movement mode.",
           "Deals 2520 Physical Attack and additional 366 damage for each harmful buffs. Enters into chain movement mode.",
           "Deals 2800 Physical Attack and additional 407 damage for each harmful buffs. Enters into chain movement mode.",
           "Deals 3108 Physical Attack and additional 454 damage for each harmful buffs. Enters into chain movement mode.",
           "Deals 3450 Physical Attack and additional 504 damage for each harmful buffs. Enters into chain movement mode.",
           "Deals 3833 Physical Attack and additional 560 damage for each harmful buffs. Enters into chain movement mode."
       ],
       ["Deals 2629 physical damage to enemies with 4m radius. If you spent at least one skill point on skill [Misdirection], damage received decrease by 75% for 10 seconds.",
           "Deals 2918 physical damage to enemies with 4m radius. If you spent at least one skill point on skill [Misdirection], damage received decrease by 75% for 12 seconds.",
           "Deals 3424 physical damage to enemies with 4m radius. If you spent at least one skill point on skill [Misdirection], damage received decrease by 75% for 14 seconds.",
           "Deals 3600 physical damage to enemies with 4m radius. If you spent at least one skill point on skill [Misdirection], damage received decrease by 75% for 16 seconds.",
           "Deals 4001 physical damage to enemies with 4m radius. If you spent at least one skill point on skill [Misdirection], damage received decrease by 75% for 18 seconds.",
           "Deals 4216 physical damage to enemies with 4m radius. If you spent at least one skill point on skill [Misdirection], damage received decrease by 75% for 20 seconds."
       ],
       ["Maximizes the capacity of dual pistols, increases physical damage by 40% for 8 seconds. However, durability decreases rate will increase by 20%",
           "Maximizes the capacity of dual pistols, increases physical damage by 45% for 8 seconds. However, durability decreases rate will increase by 25%",
           "Maximizes the capacity of dual pistols, increases physical damage by 50% for 8 seconds. However, durability decreases rate will increase by 30%",
           "Maximizes the capacity of dual pistols, increases physical damage by 55% for 8 seconds. However, durability decreases rate will increase by 35%",
           "Maximizes the capacity of dual pistols, increases physical damage by 60% for 8 seconds. However, durability decreases rate will increase by 40%"
       ],
       ["Shoot wildly to deal 3867 damage to nearby enemies and instill Fear 3 sec. The skill user then hides within the smokescreen.",
           "Shoot wildly to deal 4294 damage to nearby enemies and instill Fear 3 sec. The skill user then hides within the smokescreen.",
           "Shoot wildly to deal 4772 damage to nearby enemies and instill Fear 3 sec. The skill user then hides within the smokescreen.",
           "Shoot wildly to deal 5028 damage to nearby enemies and instill Fear 3 sec. The skill user then hides within the smokescreen."
       ],
       ["Inflicts 2760 physical damage, adds 447 extra damage per one buff effect of a target, and plants a bomb on the target. The bomb hinders the target from attacking and using skills and after 5 seconds, it adds 2070 damage upon exploding.",
           "Inflicts 3066 physical damage, adds 496 extra damage per one buff effect of a target, and plants a bomb on the target. The bomb hinders the target from attacking and using skills and after 5 seconds, it adds 2300 damage upon exploding."
       ]
   ],
   cd: [
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [150, 150, 150, 150, 150, 150, 150, 150, 150, 150],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [120, 120, 120, 120, 120, 120, 120, 120, 120, 120],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [240, 240, 240, 240, 240, 240, 240, 240, 240, 240],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
       [120, 120, 120, 120, 120, 120, 120, 120, 120, 120],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [300, 300, 300, 300, 300, 300, 300, 300, 300, 300],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [120, 120, 120, 120, 120, 120, 120, 120, 120],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [40, 40, 40, 40, 40, 40, 40],
       [60, 60, 60, 60, 60, 60],
       [60, 60, 60, 60, 60, 60],
       [90, 90, 90, 90, 90],
       [110, 110, 110, 110],
       [90, 90]
   ],
   mp: [
       [37, 45, 60, 78, 98, 121, 146, 177, 216, 261, 315, 371, 437, 508, 589, 676],
       [69, 92, 121, 151, 187, 227, 275, 336, 405, 489, 578, 680, 790, 916, 1046, 1182],
       [40, 52, 64, 79, 96, 115, 138, 165, 198, 233],
       [70, 87, 107, 131, 157, 189, 226, 271, 324, 378, 442, 508, 582, 662, 737, 819],
       [26, 32, 39, 48, 57, 69, 83, 99, 117, 136],
       [113, 141, 174, 211, 255, 311, 376, 454, 536, 632, 734, 850, 976, 1099, 1236, 1390],
       [155, 190, 230, 278, 339, 411, 490, 578, 682, 789, 914, 1043, 1173, 1318, 1482, 1653, ],
       [51, 62, 76, 92, 111, 134, 159, 188, 219, 253, 290, 330, 370, 416, 467, 518],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [110, 132, 158, 190, 224, 262, 306, 350, 402, 453],
       [138, 166, 202, 244, 288, 341, 397, 460, 527, 599, 674, 757, 849, 943, 1048, 1165],
       [280, 338, 408, 481, 567, 659, 764, 877, 987, 1110, 1248, 1395, 1549, 1721, 1912, 2123],
       [86, 104, 124, 146, 171, 198, 230, 260, 293, 328],
       [146, 176, 208, 245, 285, 331, 379, 427, 480, 540],
       [128, 152, 180, 211, 244, 283, 320, 360, 404, 454],
       [216, 252, 295, 338, 388, 441, 491, 546, 608, 672],
       [319, 376, 444, 515, 597, 685, 771, 867, 975, 1089, 1211, 1344, 1494, 1659, 1842, 1993],
       [397, 460, 527, 599, 674, 757, 849, 943, 1048, 1165],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [859, 957, 1065, 1184, 1313, 1443, 1586, 1742, 1913, 2102, 2011],
       [565, 635, 714, 803, 895, 994, 1103, 1226, 1361, 1513, 1594],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1286, 1445, 1612, 1790, 1986, 2207, 2450, 2724, 2870],
       [828, 928, 1032, 1147, 1274, 1414, 1570, 1744],
       [1193, 1327, 1474, 1638, 1818, 2018, 2242],
       [1474, 1638, 1820, 2020, 2243, 2491],
       [1709, 1897, 2017, 2340, 2601, 2740],
       [2077, 2282, 2506, 27252, 2884],
       [2011, 2233, 2481, 2615],
       [2685, 2981]
   ],
   cast: [
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0]
   ],
   skillLevel: [
       [1, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60],
       [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64],
       [6, 10, 14, 18, 22, 26, 30, 34, 38, 42],
       [8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68],
       [10, 14, 18, 22, 26, 30, 34, 38, 42, 46],
       [12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72],
       [17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77],
       [19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67, 71, 75, 79],
       [21, 25, 29, 33, 37, 41, 45, 49, 53, 57],
       [23, 27, 31, 35, 39, 43, 47, 51, 55, 59],
       [25, 29, 33, 37, 41, 45, 49, 53, 57, 61],
       [27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67, 71, 75, 79, 83, 87],
       [32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92],
       [34, 38, 42, 46, 50, 54, 58, 62, 66, 70],
       [36, 40, 44, 48, 52, 56, 60, 64, 68, 72],
       [38, 42, 46, 50, 54, 58, 62, 66, 70, 74],
       [40, 44, 48, 52, 56, 60, 64, 68, 72, 76],
       [40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 99],
       [51, 55, 59, 63, 67, 71, 75, 79, 83, 87],
       [55, 59, 63, 67, 71, 75, 79, 83, 87, 91],
       [59, 63, 67, 71, 75, 79, 83, 87, 91, 95],
       [61, 65, 69, 73, 77, 81, 85, 89, 93, 97, 99],
       [65, 69, 73, 77, 81, 85, 89, 93, 97, 99],
       [69, 73, 77, 81, 85, 89, 93, 97, 99],
       [71, 75, 79, 83, 87, 91, 95, 99],
       [75, 79, 83, 87, 91, 95, 99],
       [79, 83, 87, 91, 95, 99],
       [81, 85, 89, 93, 97, 99],
       [85, 89, 93, 97, 99],
       [89, 93, 97, 99],
       [95, 99]
   ]

};