var Rifleman = {
   skillDescription: ["Countdown", "Rupture", "Hollow Point", "Leg Shot", "Stealth", "Hawk Eye", "Crimson Bullet", "Eagle Eye", "Concentration", "Sharpshooter", "Incendiary Round", "Ambush", "Terminate",
       "Sonic Blast", "Rifle Smash", "Pinpoint Weakness", "Deploy Turret", "Headshot", "Knockout Shot", "Ultimatum", "Predator", "Spot Weakness", "Roll With It", "Go Postal", "Bloodlust", "Death Kneell",
       "Ghost Stance,", "Napalm Strike", "Multi Trap", "Bullet May Cry", "Destination"
   ],
   skillInfo: [
       ["Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 10 physical damaga and after 3 seconds, adds 51 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 13 physical damaga and after 3 seconds, adds 66 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 17 physical damaga and after 3 seconds, adds 88 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 22 physical damaga and after 3 seconds, adds 111 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 28 physical damaga and after 3 seconds, adds 138 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 35 physical damaga and after 3 seconds, adds 173 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 42 physical damaga and after 3 seconds, adds 210 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 51 physical damaga and after 3 seconds, adds 253 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 62 physical damaga and after 3 seconds, adds 309 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 75 physical damaga and after 3 seconds, adds 375 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 90 physical damaga and after 3 seconds, adds 451 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 107 physical damaga and after 3 seconds, adds 533 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 126 physical damaga and after 3 seconds, adds 628 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 146 physical damaga and after 3 seconds, adds 729 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 169 physical damaga and after 3 seconds, adds 844 extra damage to surroundings upon exploding.",
           "Shoots a special bullet that explodes in the enemy's body. The bullet inflicts 194 physical damaga and after 3 seconds, adds 969 extra damage to surroundings upon exploding."
       ],
       ["Inflicts 47 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 57.",
           "Inflicts 63 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 77.",
           "Inflicts 79 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 98.",
           "Inflicts 98 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 121.",
           "Inflicts 123 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 155.",
           "Inflicts 150 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 193.",
           "Inflicts 181 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 233.",
           "Inflicts 221 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 283.",
           "Inflicts 268 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 343.",
           "Inflicts 322 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 413.",
           "Inflicts 381 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 487.",
           "Inflicts 448 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 575.",
           "Inflicts 520 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 685.",
           "Inflicts 603 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 802.",
           "Inflicts 692 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 923.",
           "Inflicts 778 physical damage on an enemy and by exposing its weaknesses, decreases Physical DEF by 1051."
       ],
       ["Fires an aimed shot to inflict 154 physical damage. Critical rate increases by 27.",
           "Fires an aimed shot to inflict 200 physical damage. Critical rate increases by 30.",
           "Fires an aimed shot to inflict 250 physical damage. Critical rate increases by 33.",
           "Fires an aimed shot to inflict 313 physical damage. Critical rate increases by 36.",
           "Fires an aimed shot to inflict 388 physical damage. Critical rate increases by 39.",
           "Fires an aimed shot to inflict 467 physical damage. Critical rate increases by 42.",
           "Fires an aimed shot to inflict 567 physical damage. Critical rate increases by 45.",
           "Fires an aimed shot to inflict 688 physical damage. Critical rate increases by 48.",
           "Fires an aimed shot to inflict 833 physical damage. Critical rate increases by 51.",
           "Fires an aimed shot to inflict 992 physical damage. Critical rate increases by 54.",
           "Fires an aimed shot to inflict 1167 physical damage. Critical rate increases by 57.",
           "Fires an aimed shot to inflict 1371 physical damage. Critical rate increases by 60.",
           "Fires an aimed shot to inflict 1588 physical damage. Critical rate increases by 63.",
           "Fires an aimed shot to inflict 1834 physical damage. Critical rate increases by 66.",
           "Fires an aimed shot to inflict 2084 physical damage. Critical rate increases by 69.",
           "Fires an aimed shot to inflict 2342 physical damage. Critical rate increases by 72."
       ],
       ["Deals 65 Physical damage and reduces target's movement speed by 15 for 10 seconds.",
           "Deals 81 Physical damage and reduces target's movement speed by 18 for 11 seconds.",
           "Deals 101 Physical damage and reduces target's movement speed by 21 for 12 seconds.",
           "Deals 126 Physical damage and reduces target's movement speed by 24 for 13 seconds.",
           "Deals 153 Physical damage and reduces target's movement speed by 27 for 14 seconds.",
           "Deals 185 Physical damage and reduces target's movement speed by 30 for 15 seconds.",
           "Deals 225 Physical damage and reduces target's movement speed by 33 for 16 seconds.",
           "Deals 273 Physical damage and reduces target's movement speed by 36 for 17 seconds.",
           "Deals 329 Physical damage and reduces target's movement speed by 39 for 18 seconds.",
           "Deals 389 Physical damage and reduces target's movement speed by 42 for 20 seconds."
       ],
       ["Hides for 30 sec to reset threat rate and decreases move speed by 20.",
           "Hides for 33 sec to reset threat rate and decreases move speed by 15.",
           "Hides for 36 sec to reset threat rate and decreases move speed by 10.",
           "Hides for 39 sec to reset threat rate and decreases move speed by 5.",
           "Hides for 42 sec to reset threat rate.",
           "Hides for 45 sec to reset threat rate and increases move speed by 2.",
           "Hides for 48 sec to reset threat rate and increases move speed by 4.",
           "Hides for 51 sec to reset threat rate and increases move speed by 6.",
           "Hides for 54 sec to reset threat rate and increases move speed by 8.",
           "Hides for 60 sec to reset threat rate and increases move speed by 10."
       ],
       ["Increases skill attack by 57 and skill success rate by 5% for all skills with a cast time of more than once second. Lasts for 10 minutes.",
           "Increases skill attack by 71 and skill success rate by 8% for all skills with a cast time of more than once second. Lasts for 10 minutes.",
           "Increases skill attack by 89 and skill success rate by 11% for all skills with a cast time of more than once second. Lasts for 10 minutes.",
           "Increases skill attack by 109 and skill success rate by 14% for all skills with a cast time of more than once second. Lasts for 10 minutes.",
           "Increases skill attack by 131 and skill success rate by 17% for all skills with a cast time of more than once second. Lasts for 10 minutes.",
           "Increases skill attack by 160 and skill success rate by 20% for all skills with a cast time of more than once second. Lasts for 10 minutes6.",
           "Increases skill attack by 194 and skill success rate by 23% for all skills with a cast time of more than once second. Lasts for 10 minutes.",
           "Increases skill attack by 233 and skill success rate by 26% for all skills with a cast time of more than once second. Lasts for 10 minutes.",
           "Increases skill attack by 276 and skill success rate by 29% for all skills with a cast time of more than once second. Lasts for 10 minutes.",
           "Increases skill attack by 325 and skill success rate by 32% for all skills with a cast time of more than once second. Lasts for 10 minutes.",
           "Increases skill attack by 377 and skill success rate by 35% for all skills with a cast time of more than once second. Lasts for 10 minutes.",
           "Increases skill attack by 436 and skill success rate by 38% for all skills with a cast time of more than once second. Lasts for 10 minutes.",
           "Increases skill attack by 498 and skill success rate by 41% for all skills with a cast time of more than once second. Lasts for 10 minutes.",
           "Increases skill attack by 563 and skill success rate by 44% for all skills with a cast time of more than once second. Lasts for 10 minutes.",
           "Increases skill attack by 633 and skill success rate by 47% for all skills with a cast time of more than once second. Lasts for 10 minutes.",
           "Increases skill attack by 712 and skill success rate by 50% for all skills with a cast time of more than once second. Lasts for 10 minutes."
       ],
       ["Makes an enemy bleed for 6 seconds, inflicts 66 physical damage per sec and decreases healing ability by 50%.",
           "Makes an enemy bleed for 6 seconds, inflicts 81 physical damage per sec and decreases healing ability by 52%.",
           "Makes an enemy bleed for 6 seconds, inflicts 98 physical damage per sec and decreases healing ability by 54%.",
           "Makes an enemy bleed for 6 seconds, inflicts 120 physical damage per sec and decreases healing ability by 56%.",
           "Makes an enemy bleed for 6 seconds, inflicts 145 physical damage per sec and decreases healing ability by 58%.",
           "Makes an enemy bleed for 6 seconds, inflicts 176 physical damage per sec and decreases healing ability by 60%.",
           "Makes an enemy bleed for 6 seconds, inflicts 210 physical damage per sec and decreases healing ability by 62%.",
           "Makes an enemy bleed for 6 seconds, inflicts 247 physical damage per sec and decreases healing ability by 64%.",
           "Makes an enemy bleed for 6 seconds, inflicts 292 physical damage per sec and decreases healing ability by 66%. This skill uses a special bullet that doesen't allow any spell to cancel the effects.",
           "Makes an enemy bleed for 6 seconds, inflicts 338 physical damage per sec and decreases healing ability by 68%. This skill uses a special bullet that doesen't allow any spell to cancel the effects.",
           "Makes an enemy bleed for 6 seconds, inflicts 391 physical damage per sec and decreases healing ability by 70%. This skill uses a special bullet that doesen't allow any spell to cancel the effects.",
           "Makes an enemy bleed for 6 seconds, inflicts 446 physical damage per sec and decreases healing ability by 72%. This skill uses a special bullet that doesen't allow any spell to cancel the effects.",
           "Makes an enemy bleed for 6 seconds, inflicts 502 physical damage per sec and decreases healing ability by 74%. This skill uses a special bullet that doesen't allow any spell to cancel the effects.",
           "Makes an enemy bleed for 6 seconds, inflicts 564 physical damage per sec and decreases healing ability by 76%. This skill uses a special bullet that doesen't allow any spell to cancel the effects.",
           "Makes an enemy bleed for 6 seconds, inflicts 635 physical damage per sec and decreases healing ability by 78%. This skill uses a special bullet that doesen't allow any spell to cancel the effects.",
           "Makes an enemy bleed for 6 seconds, inflicts 707 physical damage per sec and decreases healing ability by 80%. This skill uses a special bullet that doesen't allow any spell to cancel the effects."
       ],
       ["Increases your Hit Rate by 5 and your Crit Rate by 3 for 1 minute.",
           "Increases your Hit Rate by 6 and your Crit Rate by 6 for 1 minute.",
           "Increases your Hit Rate by 7 and your Crit Rate by 9 for 1 minute.",
           "Increases your Hit Rate by 8 and your Crit Rate by 12 for 1 minute.",
           "Increases your Hit Rate by 9 and your Crit Rate by 15 for 1 minute.",
           "Increases your Hit Rate by 10 and your Crit Rate by 18 for 1 minute.",
           "Increases your Hit Rate by 11 and your Crit Rate by 21 for 1 minute.",
           "Increases your Hit Rate by 12 and your Crit Rate by 24 for 1 minute.",
           "Increases your Hit Rate by 13 and your Crit Rate by 27 for 1 minute.",
           "Increases your Hit Rate by 15 and your Crit Rate by 30 for 1 minute."
       ],
       ["Increases the chance to resist casting interruption by 20% and increases hit rate by 2.",
           "Increases the chance to resist casting interruption by 32% and increases hit rate by 4.",
           "Increases the chance to resist casting interruption by 44% and increases hit rate by 6.",
           "Increases the chance to resist casting interruption by 52% and increases hit rate by 8.",
           "Increases the chance to resist casting interruption by 60% and increases hit rate by 10.",
           "Increases the chance to resist casting interruption by 68% and increases hit rate by 12.",
           "Increases the chance to resist casting interruption by 76% and increases hit rate by 14.",
           "Increases the chance to resist casting interruption by 84% and increases hit rate by 16.",
           "Increases the chance to resist casting interruption by 92% and increases hit rate by 18.",
           "Increases the chance to resist casting interruption by 100% and increases hit rate by 20."
       ],
       ["Increases critical hit damage by 10%.",
           "Increases critical hit damage by 15%.",
           "Increases critical hit damage by 20%.",
           "Increases critical hit damage by 25%.",
           "Increases critical hit damage by 30%.",
           "Increases critical hit damage by 35%.",
           "Increases critical hit damage by 40%.",
           "Increases critical hit damage by 45%.",
           "Increases critical hit damage by 50%.",
           "Increases critical hit damage by 55%."
       ],
       ["Deals 187 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 228 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 277 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 334 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 399 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 471 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 555 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 642 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 744 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 849 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 956 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 1073 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 1208 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 1344 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 1495 physical damage to all enemies within 4 meters and prevents casting for 3 seconds.",
           "Deals 1659 physical damage to all enemies within 4 meters and prevents casting for 3 seconds."
       ],
       ["Attacks the enemy from stealth to cause 327 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 393 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 476 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 578 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 682 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 803 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 938 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 1086 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 1245 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 1416 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 1590 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 1790 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 2005 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 2225 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 2475 physical damage and stun the enemy for 5 seconds.",
           "Attacks the enemy from stealth to cause 2747 physical damage and stun the enemy for 5 seconds."
       ],
       ["Shoots a target whose HP is below 25% for 525 physical damage.",
           "Shoots a target whose HP is below 25% for 639 physical damage.",
           "Shoots a target whose HP is below 25% for 767 physical damage.",
           "Shoots a target whose HP is below 25% for 907 physical damage.",
           "Shoots a target whose HP is below 25% for 1068 physical damage.",
           "Shoots a target whose HP is below 25% for 1239 physical damage.",
           "Shoots a target whose HP is below 25% for 1435 physical damage.",
           "Shoots a target whose HP is below 25% for 1638 physical damage.",
           "Shoots a target whose HP is below 25% for 1852 physical damage.",
           "Shoots a target whose HP is below 25% for 2083 physical damage.",
           "Shoots a target whose HP is below 25% for 2342 physical damage.",
           "Shoots a target whose HP is below 25% for 2622 physical damage.",
           "Shoots a target whose HP is below 25% for 2909 physical damage.",
           "Shoots a target whose HP is below 25% for 3234 physical damage.",
           "Shoots a target whose HP is below 25% for 3591 physical damage.",
           "Shoots a target whose HP is below 25% for 3987 physical damage."
       ],
       ["Deals 618 physical damage to all enemies in 4 meter radius and silences them for 6 seconds. Base critical rate of 25.",
           "Deals 749 physical damage to all enemies in 4 meter radius and silences them for 6 seconds. Base critical rate of 27.",
           "Deals 891 physical damage to all enemies in 4 meter radius and silences them for 6 seconds. Base critical rate of 29.",
           "Deals 1048 physical damage to all enemies in 4 meter radius and silences them for 7 seconds. Base critical rate of 31.",
           "Deals 1232 physical damage to all enemies in 4 meter radius and silences them for 7 seconds. Base critical rate of 33.",
           "Deals 1426 physical damage to all enemies in 4 meter radius and silences them for 7 seconds. Base critical rate of 35.",
           "Deals 1651 physical damage to all enemies in 4 meter radius and silences them for 8 seconds. Base critical rate of 37.",
           "Deals 1872 physical damage to all enemies in 4 meter radius and silences them for 8 seconds. Base critical rate of 39.",
           "Deals 2104 physical damage to all enemies in 4 meter radius and silences them for 8 seconds. Base critical rate of 41.",
           "Deals 2362 physical damage to all enemies in 4 meter radius and silences them for 9 seconds. Base critical rate of 43.",
           "Deals 2658 physical damage to all enemies in 4 meter radius and silences them for 9 seconds. Base critical rate of 45.",
           "Deals 2950 physical damage to all enemies in 4 meter radius and silences them for 9 seconds. Base critical rate of 47.",
           "Deals 3280 physical damage to all enemies in 4 meter radius and silences them for 10 seconds. Base critical rate of 49.",
           "Deals 3643 physical damage to all enemies in 4 meter radius and silences them for 10 seconds. Base critical rate of 51.",
           "Deals 4047 physical damage to all enemies in 4 meter radius and silences them for 10 seconds. Base critical rate of 53.",
           "Deals 4497 physical damage to all enemies in 4 meter radius and silences them for 10 seconds. Base critical rate of 55."
       ],
       ["Deals 182 physical damage breaks the target's concentration for 6 seconds.",
           "Deals 219 physical damage breaks the target's concentration for 7 seconds.",
           "Deals 259 physical damage breaks the target's concentration for 8 seconds.",
           "Deals 305 physical damage breaks the target's concentration for 9 seconds.",
           "Deals 354 physical damage breaks the target's concentration for 10 seconds.",
           "Deals 410 physical damage breaks the target's concentration for 11 seconds.",
           "Deals 468 physical damage breaks the target's concentration for 12 seconds.",
           "Deals 529 physical damage breaks the target's concentration for 13 seconds.",
           "Deals 595 physical damage breaks the target's concentration for 14 seconds.",
           "Deals 669 physical damage breaks the target's concentration for 15 seconds."
       ],
       ["Decreases dodge rate and critical hit resistance of target by 5 for 12 seconds, adds 10% to HP treshold for Terminate. Effects one target at a time.",
           "Decreases dodge rate and critical hit resistance of target by 7 for 12 seconds, adds 12% to HP treshold for Terminate. Effects one target at a time.",
           "Decreases dodge rate and critical hit resistance of target by 9 for 12 seconds, adds 14% to HP treshold for Terminate. Effects one target at a time.",
           "Decreases dodge rate and critical hit resistance of target by 11 for 12 seconds, adds 16% to HP treshold for Terminate. Effects one target at a time.",
           "Decreases dodge rate and critical hit resistance of target by 13 for 12 seconds, adds 18% to HP treshold for Terminate. Effects one target at a time.",
           "Decreases dodge rate and critical hit resistance of target by 15 for 12 seconds, adds 20% to HP treshold for Terminate. Effects one target at a time.",
           "Decreases dodge rate and critical hit resistance of target by 17 for 12 seconds, adds 22% to HP treshold for Terminate. Effects one target at a time.",
           "Decreases dodge rate and critical hit resistance of target by 19 for 12 seconds, adds 23% to HP treshold for Terminate. Effects one target at a time.",
           "Decreases dodge rate and critical hit resistance of target by 21 for 12 seconds, adds 24% to HP treshold for Terminate. Effects one target at a time.",
           "Decreases dodge rate and critical hit resistance of target by 25 for 12 seconds, adds 25% to HP treshold for Terminate. Effects one target at a time."
       ],
       ["Installs a fixed turret Level 40 on a selected location and lets it attack enemies within range for 40 seconds.",
           "Installs a fixed turret Level 44 on a selected location and lets it attack enemies within range for 42 seconds.",
           "Installs a fixed turret Level 48 on a selected location and lets it attack enemies within range for 44 seconds.",
           "Installs a fixed turret Level 52 on a selected location and lets it attack enemies within range for 46 seconds.",
           "Installs a fixed turret Level 56 on a selected location and lets it attack enemies within range for 48 seconds.",
           "Installs a fixed turret Level 60 on a selected location and lets it attack enemies within range for 50 seconds.",
           "Installs a fixed turret Level 64 on a selected location and lets it attack enemies within range for 52 seconds.",
           "Installs a fixed turret Level 68 on a selected location and lets it attack enemies within range for 54 seconds.",
           "Installs a fixed turret Level 72 on a selected location and lets it attack enemies within range for 56 seconds.",
           "Installs a fixed turret Level 76 on a selected location and lets it attack enemies within range for 60 seconds."
       ],
       ["By sniping an enemy, inflicts 1409 physical damage. Critical Rate increases by 50.",
           "By sniping an enemy, inflicts 1665 physical damage. Critical Rate increases by 52.",
           "By sniping an enemy, inflicts 1962 physical damage. Critical Rate increases by 54.",
           "By sniping an enemy, inflicts 2277 physical damage. Critical Rate increases by 56.",
           "By sniping an enemy, inflicts 2637 physical damage. Critical Rate increases by 58.",
           "By sniping an enemy, inflicts 3015 physical damage. Critical Rate increases by 60.",
           "By sniping an enemy, inflicts 3407 physical damage, blows off a maximum of 2517 Mana, and adds extra damage as much as Mana loss. Critical Rate increases by 62.",
           "By sniping an enemy, inflicts 3830 physical damage, blows off a maximum of 2815 Mana, and adds extra damage as much as Mana loss. Critical Rate increases by 64.",
           "By sniping an enemy, inflicts 4307 physical damage, blows off a maximum of 3152 Mana, and adds extra damage as much as Mana loss. Critical Rate increases by 66.",
           "By sniping an enemy, inflicts 4815 physical damage, blows off a maximum of 3507 Mana, and adds extra damage as much as Mana loss. Critical Rate increases by 68.",
           "By sniping an enemy, inflicts 5346 physical damage, blows off a maximum of 3878 Mana, and adds extra damage as much as Mana loss. Critical Rate increases by 70",
           "By sniping an enemy, inflicts 5940 physical damage, blows off a maximum of 4287 Mana, and adds extra damage as much as Mana loss. Critical Rate increases by 72.",
           "By sniping an enemy, inflicts 6597 physical damage, blows off a maximum of 4739 Mana, and adds extra damage as much as Mana loss. Critical Rate increases by 74.",
           "By sniping an enemy, inflicts 7263 physical damage, blows off a maximum of 5240 Mana, and adds extra damage as much as Mana loss. Critical Rate increases by 76.",
           "By sniping an enemy, inflicts 7992 physical damage, blows off a maximum of 5792 Mana, and adds extra damage as much as Mana loss. Critical Rate increases by 78.",
           "By sniping an enemy, inflicts 8802 physical damage, blows off a maximum of 6243 Mana, and adds extra damage as much as Mana loss. Critical Rate increases by 80."
       ],
       ["A blow to the head deals 512 physical damage to the target and stund it for 3 seconds.",
           "A blow to the head deals 593 physical damage to the target and stund it for 3 seconds.",
           "A blow to the head deals 686 physical damage to the target and stund it for 3 seconds.",
           "A blow to the head deals 773 physical damage to the target and stund it for 3 seconds.",
           "A blow to the head deals 867 physical damage to the target and stund it for 3 seconds.",
           "A blow to the head deals 977 physical damage to the target and stund it for 3 seconds.",
           "A blow to the head deals 1094 physical damage to the target and stund it for 3 seconds.",
           "A blow to the head deals 1214 physical damage to the target and stund it for 3 seconds.",
           "A blow to the head deals 1350 physical damage to the target and stund it for 3 seconds.",
           "A blow to the head deals 1499 physical damage to the target and stund it for 3 seconds.",
           "A blow to the head deals 1665 physical damage to the target and stund it for 3 seconds.",
           "A blow to the head deals 1848 physical damage to the target and stund it for 3 seconds.",
           "A blow to the head deals 2054 physical damage to the target and stund it for 3 seconds."
       ],
       ["Powerful finish incflicts 100 additional damage when attacking enemies whose HP is below 25%.Increases the caster's movespeed by 2.",
           "Powerful finish incflicts 150 additional damage when attacking enemies whose HP is below 25%.Increases the caster's movespeed by 2.",
           "Powerful finish incflicts 200 additional damage when attacking enemies whose HP is below 25%.Increases the caster's movespeed by 2.",
           "Powerful finish incflicts 250 additional damage when attacking enemies whose HP is below 25%.Increases the caster's movespeed by 2.",
           "Powerful finish incflicts 300 additional damage when attacking enemies whose HP is below 25%.Increases the caster's movespeed by 2.",
           "Powerful finish incflicts 350 additional damage when attacking enemies whose HP is below 25%.Increases the caster's movespeed by 2.",
           "Powerful finish incflicts 400 additional damage when attacking enemies whose HP is below 25%.Increases the caster's movespeed by 2.",
           "Powerful finish incflicts 450 additional damage when attacking enemies whose HP is below 25%.Increases the caster's movespeed by 2.",
           "Powerful finish incflicts 500 additional damage when attacking enemies whose HP is below 25%.Increases the caster's movespeed by 2.",
           "Powerful finish incflicts 550 additional damage when attacking enemies whose HP is below 25%.Increases the caster's movespeed by 2."
       ],
       ["When triggered in sniping mode, resets cool down of Stealth and lets the skill user attack enemies while hiding for 20 seconds.However, Movement Speed is decreased by 50 and the effect is cancelled after receiving damage.",
           "When triggered in sniping mode, resets cool down of Stealth and lets the skill user attack enemies while hiding for 21 seconds.However, Movement Speed is decreased by 50 and the effect is cancelled after receiving damage.",
           "When triggered in sniping mode, resets cool down of Stealth and lets the skill user attack enemies while hiding for 22 seconds.However, Movement Speed is decreased by 50 and the effect is cancelled after receiving damage.",
           "When triggered in sniping mode, resets cool down of Stealth and lets the skill user attack enemies while hiding for 23 seconds.However, Movement Speed is decreased by 50 and the effect is cancelled after receiving damage.",
           "When triggered in sniping mode, resets cool down of Stealth and lets the skill user attack enemies while hiding for 24 seconds.However, Movement Speed is decreased by 50 and the effect is cancelled after receiving damage.",
           "When triggered in sniping mode, resets cool down of Stealth and lets the skill user attack enemies while hiding for 25 seconds.However, Movement Speed is decreased by 50 and the effect is cancelled after receiving damage.",
           "When triggered in sniping mode, resets cool down of Stealth and lets the skill user attack enemies while hiding for 26 seconds.However, Movement Speed is decreased by 50 and the effect is cancelled after receiving damage.",
           "When triggered in sniping mode, resets cool down of Stealth and lets the skill user attack enemies while hiding for 27 seconds.However, Movement Speed is decreased by 50 and the effect is cancelled after receiving damage.",
           "When triggered in sniping mode, resets cool down of Stealth and lets the skill user attack enemies while hiding for 28 seconds.However, Movement Speed is decreased by 50 and the effect is cancelled after receiving damage.",
           "When triggered in sniping mode, resets cool down of Stealth and lets the skill user attack enemies while hiding for 29 seconds.However, Movement Speed is decreased by 50 and the effect is cancelled after receiving damage.",
           "When triggered in sniping mode, resets cool down of Stealth and lets the skill user attack enemies while hiding for 30 seconds.However, Movement Speed is decreased by 50 and the effect is cancelled after receiving damage."
       ],
       ["Exposes a weakness in the target's armor 2 times for 2 minutes.",
           "Exposes a weakness in the target's armor 3 times for 2 minutes.",
           "Exposes a weakness in the target's armor 4 times for 2 minutes.",
           "Exposes a weakness in the target's armor 5 times for 2 minutes.",
           "Exposes a weakness in the target's armor 6 times for 2 minutes.",
           "Exposes a weakness in the target's armor 7 times for 2 minutes.",
           "Exposes a weakness in the target's armor 8 times for 2 minutes.",
           "Exposes a weakness in the target's armor 9 times for 2 minutes.",
           "Exposes a weakness in the target's armor 10 times for 2 minutes.",
           "Exposes a weakness in the target's armor 12 times for 2 minutes."
       ],
       ["Increases critical and double attack resistance by 3.",
           "Increases critical and double attack resistance by 6.",
           "Increases critical and double attack resistance by 9.",
           "Increases critical and double attack resistance by 12.",
           "Increases critical and double attack resistance by 15.",
           "Increases critical and double attack resistance by 18.",
           "Increases critical and double attack resistance by 21.",
           "Increases critical and double attack resistance by 24.",
           "Increases critical and double attack resistance by 27.",
           "Increases critical and double attack resistance by 30."
       ],
       ["Inflicts 2575 physical damage on enemies within 4m of the target. Each blow adds 490 extra damage for 6 seconds. Critical Rate increases by 25.",
           "Inflicts 2898 physical damage on enemies within 4m of the target. Each blow adds 552 extra damage for 6 seconds. Critical Rate increases by 27.",
           "Inflicts 3226 physical damage on enemies within 4m of the target. Each blow adds 614 extra damage for 6 seconds. Critical Rate increases by 29.",
           "Inflicts 3587 physical damage on enemies within 4m of the target. Each blow adds 683 extra damage for 6 seconds. Critical Rate increases by 31.",
           "Inflicts 3982 physical damage on enemies within 4m of the target. Each blow adds 758 extra damage for 6 seconds. Critical Rate increases by 33.",
           "Inflicts 4423 physical damage on enemies within 4m of the target. Each blow adds 842 extra damage for 6 seconds. Critical Rate increases by 35.",
           "Inflicts 4910 physical damage on enemies within 4m of the target. Each blow adds 935 extra damage for 6 seconds. Critical Rate increases by 37.",
           "Inflicts 5456 physical damage on enemies within 4m of the target. Each blow adds 1039 extra damage for 6 seconds. Critical Rate increases by 39.",
           "Inflicts 5750 physical damage on enemies within 4m of the target. Each blow adds 1095 extra damage for 6 seconds. Critical Rate increases by 41."
       ],
       ["Deals 1302 Physical Attack and converts 80% of the damage value to own HP. if the target is killed with this skill, recovers additional HP equivalent to 25% of Max HP.",
           "Deals 1458 Physical Attack and converts 85% of the damage value to own HP. if the target is killed with this skill, recovers additional HP equivalent to 30% of Max HP.",
           "Deals 1618 Physical Attack and converts 90% of the damage value to own HP. if the target is killed with this skill, recovers additional HP equivalent to 35% of Max HP.",
           "Deals 1800 Physical Attack and converts 95% of the damage value to own HP. if the target is killed with this skill, recovers additional HP equivalent to 40% of Max HP.",
           "Deals 1998 Physical Attack and converts 100% of the damage value to own HP. if the target is killed with this skill, recovers additional HP equivalent to 45% of Max HP.",
           "Deals 2220 Physical Attack and converts 105% of the damage value to own HP. if the target is killed with this skill, recovers additional HP equivalent to 50% of Max HP.",
           "Deals 2464 Physical Attack and converts 110% of the damage value to own HP. if the target is killed with this skill, recovers additional HP equivalent to 55% of Max HP.",
           "Deals 2738 Physical Attack and converts 120% of the damage value to own HP. if the target is killed with this skill, recovers additional HP equivalent to 60% of Max HP."
       ],
       ["Deals 2552 Physical Attack and instantly kills an elite monster with 39% probability. Deals double damage to a players with 26% probability.",
           "Deals 2832 Physical Attack and instantly kills an elite monster with 45% probability. Deals double damage to a players with 30% probability.",
           "Deals 3150 Physical Attack and instantly kills an elite monster with 51% probability. Deals double damage to a players with 34% probability.",
           "Deals 3497 Physical Attack and instantly kills an elite monster with 57% probability. Deals double damage to a players with 38% probability.",
           "Deals 3885 Physical Attack and instantly kills an elite monster with 63% probability. Deals double damage to a players with 42% probability.",
           "Deals 4312 Physical Attack and instantly kills an elite monster with 69% probability. Deals double damage to a players with 46% probability.",
           "Deals 4792 Physical Attack and instantly kills an elite monster with 75% probability. Deals double damage to a players with 50% probability."
       ],
       ["Right after inflicting 2225 physical damage, the user goes into Ghost Stance and hides itself for 6 seconds. Movement Speed inceases by 10.",
           "Right after inflicting 2475 physical damage, the user goes into Ghost Stance and hides itself for 6 seconds. Movement Speed inceases by 10.",
           "Right after inflicting 2747 physical damage, the user goes into Ghost Stance and hides itself for 6 seconds. Movement Speed inceases by 10.",
           "Right after inflicting 3053 physical damage, the user goes into Ghost Stance and hides itself for 6 seconds. Movement Speed inceases by 10.",
           "Right after inflicting 3388 physical damage, the user goes into Ghost Stance and hides itself for 6 seconds. Movement Speed inceases by 10.",
           "Right after inflicting 3765 physical damage, the user goes into Ghost Stance and hides itself for 6 seconds. Movement Speed inceases by 10."
       ],
       ["Shoots a bullet that heats the ground. It deals 2562 damage to enemies within a 6m radius and the armor of the damaged enemies is melted fo 10 seconds.",
           "Shoots a bullet that heats the ground. It deals 2844 damage to enemies within a 6m radius and the armor of the damaged enemies is melted fo 12 seconds.",
           "Shoots a bullet that heats the ground. It deals 3159 damage to enemies within a 6m radius and the armor of the damaged enemies is melted fo 14 seconds.",
           "Shoots a bullet that heats the ground. It deals 3507 damage to enemies within a 6m radius and the armor of the damaged enemies is melted fo 16 seconds.",
           "Shoots a bullet that heats the ground. It deals 3897 damage to enemies within a 6m radius and the armor of the damaged enemies is melted fo 18 seconds."
       ],
       ["Deals 1896 physical damage to a target and enemies within 6 meters and slow them down by 18 for 4 seconds",
           "Deals 2106 physical damage to a target and enemies within 6 meters and slow them down by 21 for 5 seconds",
           "Deals 2338 physical damage to a target and enemies within 6 meters and slow them down by 24 for 6 seconds",
           "Deals 2598 physical damage to a target and enemies within 6 meters and slow them down by 27 for 7 seconds"
       ],
       ["Imbue the gun barrel with awesome power for 8 seconds. Increase double attack value by 14, ignores 24% of enemy's physical DEF, and adds splash damage to normal attacks equivalent to 80% of physical ATK.",
           "Imbue the gun barrel with awesome power for 8 seconds. Increase double attack value by 16, ignores 26% of enemy's physical DEF, and adds splash damage to normal attacks equivalent to 80% of physical ATK.",
           "Imbue the gun barrel with awesome power for 8 seconds. Increase double attack value by 18, ignores 28% of enemy's physical DEF, and adds splash damage to normal attacks equivalent to 80% of physical ATK.",
           "Imbue the gun barrel with awesome power for 8 seconds. Increase double attack value by 20, ignores 30% of enemy's physical DEF, and adds splash damage to normal attacks equivalent to 80% of physical ATK."
       ],
       ["By shooting an enemy with special bullet, completely ignores its Physical DEF and inflicts 2587 physical damage. Adds 4312 extra damage when using the skill while hiding.",
           "By shooting an enemy with special bullet, completely ignores its Physical DEF and inflicts 2875 physical damage. Adds 4792 extra damage when using the skill while hiding."
       ]
   ],
   cd: [
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [12, 11, 10, 9, 8, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [120, 120, 120, 120, 120, 120, 120, 120, 120, 120],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [120, 120, 120, 120, 120, 120, 120, 120, 120, 120],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [20, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120],
       [90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150],
       [120, 120, 120, 120, 120, 120, 120, 120, 120, 120],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [120, 120, 120, 120, 120, 120, 120, 120, 120],
       [20, 20, 20, 20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30, 30],
       [90, 90, 90, 90, 90, 90],
       [60, 60, 60, 60, 60],
       [60, 55, 50, 45, 40],
       [120, 120, 120, 120],
       [90, 90]
   ],
   mp: [
       [33, 43, 57, 72, 90, 112, 137, 164, 201, 244, 293, 346, 408, 474, 549, 630],
       [34, 45, 57, 70, 88, 107, 129, 157, 190, 229, 271, 319, 370, 429, 490, 553],
       [80, 104, 130, 163, 202, 243, 295, 358, 433, 516, 607, 713, 826, 954, 1084, 1218],
       [46, 57, 71, 88, 107, 130, 158, 191, 230, 272],
       [23, 29, 35, 43, 51, 61, 74, 88, 104, 122],
       [77, 95, 117, 140, 168, 202, 242, 289, 338, 394, 453, 520, 591, 658, 732, 814],
       [132, 162, 196, 240, 290, 352, 420, 494, 584, 676, 782, 892, 1004, 1128, 1270, 1414],
       [74, 90, 108, 129, 155, 185, 217, 253, 292, 335],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [123, 150, 182, 220, 262, 310, 366, 422, 490, 558, 629, 706, 795, 885, 984, 1091],
       [106, 128, 155, 188, 222, 261, 305, 353, 409, 460, 517, 582, 652, 723, 804, 893],
       [128, 155, 187, 221, 260, 302, 350, 402, 452, 508, 571, 639, 709, 788, 875, 972],
       [260, 315, 374, 440, 517, 599, 692, 786, 884, 992, 1115, 1239, 1378, 1530, 1700, 1889],
       [66, 80, 94, 111, 129, 149, 169, 192, 216, 243],
       [57, 68, 80, 94, 109, 126, 143, 161, 180, 203],
       [362, 422, 493, 566, 650, 739, 822, 914, 1018, 1126],
       [806, 950, 1117, 1294, 1496, 1715, 1925, 2160, 2424, 2705, 2998, 3324, 3684, 4084, 4527, 4890],
       [266, 308, 353, 402, 451, 508, 569, 631, 702, 779, 866, 961, 1068],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1150, 1282, 1426, 1586, 1759, 1932, 2124, 2334, 2562, 2813, 2813],
       [404, 450, 501, 557, 614, 675, 741, 814, 894, 982],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1004, 1130, 1258, 1399, 1553, 1725, 1915, 2128, 2243],
       [677, 758, 841, 936, 1039, 1154, 1281, 1424],
       [1327, 1473, 1638, 1818, 2020, 2242, 2492],
       [1157, 1287, 1428, 1588, 1762, 1958],
       [1332, 1479, 1643, 1824, 2026],
       [1327, 1474, 1637, 1819],
       [1630, 1790, 1966, 2060],
       [2494, 2771]
   ],
   cast: [
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1]
   ],
   skillLevel: [
       [1, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60],
       [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64],
       [6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66],
       [8, 12, 16, 20, 24, 28, 32, 36, 40, 44],
       [10, 14, 18, 22, 26, 30, 34, 38, 42, 46],
       [12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72],
       [17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77],
       [19, 23, 27, 31, 35, 39, 43, 47, 51, 55],
       [21, 25, 29, 33, 37, 41, 45, 49, 53, 57],
       [23, 27, 31, 35, 39, 43, 47, 51, 55, 59],
       [25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77, 81, 85],
       [27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67, 71, 75, 79, 83, 87],
       [32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92],
       [34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74, 78, 82, 86, 90, 94],
       [36, 40, 44, 48, 52, 56, 60, 64, 68, 72],
       [38, 42, 46, 50, 54, 58, 62, 66, 70, 74],
       [40, 44, 48, 52, 56, 60, 64, 68, 72, 76],
       [40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 99],
       [51, 55, 59, 63, 67, 71, 75, 79, 83, 87, 91, 95, 99],
       [55, 59, 63, 67, 71, 75, 79, 83, 87, 91],
       [59, 63, 67, 71, 75, 79, 83, 87, 91, 95, 99],
       [61, 65, 69, 73, 77, 81, 85, 89, 93, 97],
       [65, 69, 73, 77, 81, 85, 89, 93, 97, 99],
       [69, 73, 77, 81, 85, 89, 93, 97, 99],
       [71, 75, 79, 83, 87, 91, 95, 99],
       [75, 79, 83, 87, 91, 95, 99],
       [79, 83, 87, 91, 95, 99],
       [81, 85, 89, 93, 97],
       [85, 89, 93, 97],
       [89, 93, 97, 99],
       [95, 99]
   ]


};