var Warlock = {
   skillDescription: ["FireBall", "Enervate", "Polymorph", "Lighting Orb", "Mana Shield", "Hellfire", "Aetheric Shackles", "Black Harvest", "Mana Torrent", "Meditate", "Shadow Fall", "Soul Trap",
       "Aether Flare", "Inferno", "Nightmare", "Rend Soul", "Mass Teleport", "Meteor", "Mirrored Agony", "Ahriman's Blessing", "Calamity", "Incinerate", "Focus Magic", "Volt Rain", "Shadow Mist", "Black Hole",
       "Ruinous Thunder", "Mana Barbs", "Blizzard", "Black Twister", "Abyssal Gate"
   ],
   skillInfo: [
       ["Deals 75 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 25.",
           "Deals 94 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 27.",
           "Deals 127 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 29.",
           "Deals 161 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 31.",
           "Deals 199 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 33.",
           "Deals 246 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 35.",
           "Deals 299 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 37.",
           "Deals 362 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 39.",
           "Deals 439 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 41.",
           "Deals 531 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 43.",
           "Deals 640 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 45.",
           "Deals 756 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 47.",
           "Deals 892 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 49.",
           "Deals 1037 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 51.",
           "Deals 1199 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 53.",
           "Deals 1380 fire magic damage and gives fire debuff for 3 seconds. Base critical rate of 55."
       ],
       ["Deals 44 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 59 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 75 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 93 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 115 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 140 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 169 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 205 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 248 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 299 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 353 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 417 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 485 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 561 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 641 magic damage per second for 6 seconds and gives dark debuff.",
           "Deals 725 magic damage per second for 6 seconds and gives dark debuff."
       ],
       ["Turns the target into a cute defenseless bunny and decreases move speed by 20 for 20 seconds. Can only polymorph one target and cannot be auto cast.",
           "Turns the target into a cute defenseless bunny and decreases move speed by 22 for 22 seconds. Can only polymorph one target and cannot be auto cast.",
           "Turns the target into a cute defenseless bunny and decreases move speed by 24 for 24 seconds. Can only polymorph one target and cannot be auto cast.",
           "Turns the target into a cute defenseless bunny and decreases move speed by 26 for 26 seconds. Can only polymorph one target and cannot be auto cast.",
           "Turns the target into a cute defenseless bunny and decreases move speed by 28 for 28 seconds. Can only polymorph one target and cannot be auto cast.",
           "Turns the target into a cute defenseless bunny and decreases move speed by 30 for 30 seconds. Can only polymorph one target and cannot be auto cast.",
           "Turns the target into a cute defenseless bunny and decreases move speed by 32 for 32 seconds. Can only polymorph one target and cannot be auto cast.",
           "Turns the target into a cute defenseless bunny and decreases move speed by 34 for 34 seconds. Can only polymorph one target and cannot be auto cast.",
           "Turns the target into a cute defenseless bunny and decreases move speed by 36 for 36 seconds. Can only polymorph one target and cannot be auto cast.",
           "Turns the target into a cute defenseless bunny and decreases move speed by 40 for 38 seconds. Can only polymorph one target and cannot be auto cast."
       ],
       ["Deals 94 magic damage and decreases move speed by 15 for 3 seconds. Gives lighting debuff.",
           "Deals 118 magic damage and decreases move speed by 16 for 3 seconds. Gives lighting debuff.",
           "Deals 147 magic damage and decreases move speed by 17 for 3 seconds. Gives lighting debuff.",
           "Deals 181 magic damage and decreases move speed by 18 for 3 seconds. Gives lighting debuff.",
           "Deals 220 magic damage and decreases move speed by 19 for 3 seconds. Gives lighting debuff.",
           "Deals 267 magic damage and decreases move speed by 20 for 3 seconds. Gives lighting debuff.",
           "Deals 324 magic damage and decreases move speed by 21 for 3 seconds. Gives lighting debuff.",
           "Deals 391 magic damage and decreases move speed by 22 for 3 seconds. Gives lighting debuff.",
           "Deals 472 magic damage and decreases move speed by 23 for 3 seconds. Gives lighting debuff.",
           "Deals 557 magic damage and decreases move speed by 24 for 3 seconds. Gives lighting debuff.",
           "Deals 658 magic damage and decreases move speed by 25 for 3 seconds. Gives lighting debuff.",
           "Deals 764 magic damage and decreases move speed by 26 for 3 seconds. Gives lighting debuff.",
           "Deals 884 magic damage and decreases move speed by 27 for 3 seconds. Gives lighting debuff.",
           "Deals 1010 magic damage and decreases move speed by 28 for 3 seconds. Gives lighting debuff.",
           "Deals 1143 magic damage and decreases move speed by 29 for 3 seconds. Gives lighting debuff.",
           "Deals 1283 magic damage and decreases move speed by 30 for 3 seconds. Gives lighting debuff."
       ],
       ["Reduces 30% of damage taken at a cost of 2.25 times the mana instead",
           "Reduces 32% of damage taken at a cost of 2.2 times the mana instead",
           "Reduces 34% of damage taken at a cost of 2.15 times the mana instead",
           "Reduces 36% of damage taken at a cost of 2.1 times the mana instead",
           "Reduces 38% of damage taken at a cost of 2.05 times the mana instead",
           "Reduces 40% of damage taken at a cost of 2 times the mana instead",
           "Reduces 42% of damage taken at a cost of 1.95 times the mana instead",
           "Reduces 44% of damage taken at a cost of 1.9 times the mana instead",
           "Reduces 46% of damage taken at a cost of 1.85 times the mana instead",
           "Reduces 48% of damage taken at a cost of 1.8 times the mana instead",
           "Reduces 50% of damage taken at a cost of 1.75 times the mana instead",
           "Reduces 52% of damage taken at a cost of 1.7 times the mana instead",
           "Reduces 54% of damage taken at a cost of 1.65 times the mana instead",
           "Reduces 56% of damage taken at a cost of 1.6 times the mana instead",
           "Reduces 58% of damage taken at a cost of 1.55 times the mana instead",
           "Reduces 60% of damage taken at a cost of 1.5 times the mana instead"
       ],
       ["Deals 213 magic damage and stuns for 3 seconds. Deals additional 107 magic damage to fire debuffed targets.",
           "Deals 265 magic damage and stuns for 3 seconds. Deals additional 133 magic damage to fire debuffed targets.",
           "Deals 327 magic damage and stuns for 3 seconds. Deals additional 164 magic damage to fire debuffed targets.",
           "Deals 397 magic damage and stuns for 3 seconds. Deals additional 199 magic damage to fire debuffed targets.",
           "Deals 481 magic damage and stuns for 3 seconds. Deals additional 241 magic damage to fire debuffed targets.",
           "Deals 583 magic damage and stuns for 3 seconds. Deals additional 292 magic damage to fire debuffed targets.",
           "Deals 705 magic damage and stuns for 3 seconds. Deals additional 353 magic damage to fire debuffed targets.",
           "Deals 851 magic damage and stuns for 3 seconds. Deals additional 426 magic damage to fire debuffed targets.",
           "Deals 1004 magic damage and stuns for 3 seconds. Deals additional 502 magic damage to fire debuffed targets.",
           "Deals 1185 magic damage and stuns for 3 seconds. Deals additional 593 magic damage to fire debuffed targets.",
           "Deals 1377 magic damage and stuns for 3 seconds. Deals additional 689 magic damage to fire debuffed targets.",
           "Deals 1593 magic damage and stuns for 3 seconds. Deals additional 797 magic damage to fire debuffed targets.",
           "Deals 1820 magic damage and stuns for 3 seconds. Deals additional 910 magic damage to fire debuffed targets.",
           "Deals 2060 magic damage and stuns for 3 seconds. Deals additional 1030 magic damage to fire debuffed targets.",
           "Deals 2314 magic damage and stuns for 3 seconds. Deals additional 1157 magic damage to fire debuffed targets.",
           "Deals 2603 magic damage and stuns for 3 seconds. Deals additional 1302 magic damage to fire debuffed targets."
       ],
       ["Deals 104 magic damage and silences for 3 seconds. Silence duration doubles if target is casting. Deals additional 21 magic damage to dark debuffed targets.",
           "Deals 128 magic damage and silences for 4 seconds. Silence duration doubles if target is casting. Deals additional 26 magic damage to dark debuffed targets.",
           "Deals 154 magic damage and silences for 5 seconds. Silence duration doubles if target is casting. Deals additional 31 magic damage to dark debuffed targets.",
           "Deals 187 magic damage and silences for 6 seconds. Silence duration doubles if target is casting. Deals additional 37 magic damage to dark debuffed targets.",
           "Deals 227 magic damage and silences for 7 seconds. Silence duration doubles if target is casting. Deals additional 45 magic damage to dark debuffed targets.",
           "Deals 275 magic damage and silences for 8 seconds. Silence duration doubles if target is casting. Deals additional 55 magic damage to dark debuffed targets.",
           "Deals 328 magic damage and silences for 9 seconds. Silence duration doubles if target is casting. Deals additional 66 magic damage to dark debuffed targets.",
           "Deals 387 magic damage and silences for 10 seconds. Silence duration doubles if target is casting. Deals additional 77 magic damage to dark debuffed targets.",
           "Deals 457 magic damage and silences for 11 seconds. Silence duration doubles if target is casting. Deals additional 91 magic damage to dark debuffed targets.",
           "Deals 529 magic damage and silences for 12 seconds. Silence duration doubles if target is casting. Deals additional 106 magic damage to dark debuffed targets."
       ],
       ["Deals 173 magic damage and absorbs 100% of inflicted HP. Decreases HP recovery rate by 25% for 6 seconds. Deals additional 35 magic damage to dark debuffed targets.",
           "Deals 210 magic damage and absorbs 105% of inflicted HP. Decreases HP recovery rate by 28% for 6 seconds. Deals additional 42 magic damage to dark debuffed targets.",
           "Deals 255 magic damage and absorbs 110% of inflicted HP. Decreases HP recovery rate by 31% for 6 seconds. Deals additional 51 magic damage to dark debuffed targets.",
           "Deals 309 magic damage and absorbs 115% of inflicted HP. Decreases HP recovery rate by 34% for 6 seconds. Deals additional 62 magic damage to dark debuffed targets.",
           "Deals 375 magic damage and absorbs 120% of inflicted HP. Decreases HP recovery rate by 37% for 6 seconds. Deals additional 75 magic damage to dark debuffed targets.",
           "Deals 453 magic damage and absorbs 125% of inflicted HP. Decreases HP recovery rate by 40% for 6 seconds. Deals additional 91 magic damage to dark debuffed targets.",
           "Deals 536 magic damage and absorbs 130% of inflicted HP. Decreases HP recovery rate by 43% for 6 seconds. Deals additional 107 magic damage to dark debuffed targets.",
           "Deals 633 magic damage and absorbs 135% of inflicted HP. Decreases HP recovery rate by 46% for 6 seconds. Deals additional 127 magic damage to dark debuffed targets.",
           "Deals 738 magic damage and absorbs 140% of inflicted HP. Decreases HP recovery rate by 49% for 6 seconds. Deals additional 148 magic damage to dark debuffed targets.",
           "Deals 854 magic damage and absorbs 145% of inflicted HP. Decreases HP recovery rate by 52% for 6 seconds. Deals additional 171 magic damage to dark debuffed targets.",
           "Deals 980 magic damage and absorbs 150% of inflicted HP. Decreases HP recovery rate by 55% for 6 seconds. Deals additional 196 magic damage to dark debuffed targets.",
           "Deals 1113 magic damage and absorbs 155% of inflicted HP. Decreases HP recovery rate by 58% for 6 seconds. Deals additional 223 magic damage to dark debuffed targets.",
           "Deals 1250 magic damage and absorbs 160% of inflicted HP. Decreases HP recovery rate by 61% for 6 seconds. Deals additional 250 magic damage to dark debuffed targets.",
           "Deals 1406 magic damage and absorbs 165% of inflicted HP. Decreases HP recovery rate by 64% for 6 seconds. Deals additional 281 magic damage to dark debuffed targets.",
           "Deals 1575 magic damage and absorbs 170% of inflicted HP. Decreases HP recovery rate by 67% for 6 seconds. Deals additional 315 magic damage to dark debuffed targets.",
           "Deals 1749 magic damage and absorbs 175% of inflicted HP. Decreases HP recovery rate by 70% for 6 seconds. Deals additional 350 magic damage to dark debuffed targets."
       ],
       ["Overlaps Mana, increases Magic ATK by 5. An attack ignores 2% of Magic DEF buy consumes 3 extra MP.",
           "Overlaps Mana, increases Magic ATK by 10. An attack ignores 3% of Magic DEF buy consumes 6 extra MP.",
           "Overlaps Mana, increases Magic ATK by 15. An attack ignores 3% of Magic DEF buy consumes 9 extra MP.",
           "Overlaps Mana, increases Magic ATK by 20. An attack ignores 4% of Magic DEF buy consumes 12 extra MP.",
           "Overlaps Mana, increases Magic ATK by 25. An attack ignores 4% of Magic DEF buy consumes 15 extra MP.",
           "Overlaps Mana, increases Magic ATK by 30. An attack ignores 5% of Magic DEF buy consumes 18 extra MP.",
           "Overlaps Mana, increases Magic ATK by 35. An attack ignores 5% of Magic DEF buy consumes 21 extra MP.",
           "Overlaps Mana, increases Magic ATK by 40. An attack ignores 6% of Magic DEF buy consumes 24 extra MP.",
           "Overlaps Mana, increases Magic ATK by 45. An attack ignores 6% of Magic DEF buy consumes 27 extra MP.",
           "Overlaps Mana, increases Magic ATK by 50. An attack ignores 7% of Magic DEF buy consumes 30 extra MP."
       ],
       ["Harmonizes Mana, adds 6% of Max MP to max HP. The Max MP increase from buff is excluded from the effect",
           "Harmonizes Mana, adds 7% of Max MP to max HP. The Max MP increase from buff is excluded from the effect",
           "Harmonizes Mana, adds 8% of Max MP to max HP. The Max MP increase from buff is excluded from the effect",
           "Harmonizes Mana, adds 9% of Max MP to max HP. The Max MP increase from buff is excluded from the effect",
           "Harmonizes Mana, adds 10% of Max MP to max HP. The Max MP increase from buff is excluded from the effect",
           "Harmonizes Mana, adds 11% of Max MP to max HP. The Max MP increase from buff is excluded from the effect",
           "Harmonizes Mana, adds 12% of Max MP to max HP. The Max MP increase from buff is excluded from the effect",
           "Harmonizes Mana, adds 13% of Max MP to max HP. The Max MP increase from buff is excluded from the effect",
           "Harmonizes Mana, adds 14% of Max MP to max HP. The Max MP increase from buff is excluded from the effect",
           "Harmonizes Mana, adds 15% of Max MP to max HP. The Max MP increase from buff is excluded from the effect"
       ],
       ["Deals 68 magic damage per second for 10 seconds to targets in range. Deals additional 7 magic damage to dark debuffed targets.",
           "Deals 82 magic damage per second for 10 seconds to targets in range. Deals additional 8 magic damage to dark debuffed targets.",
           "Deals 100 magic damage per second for 10 seconds to targets in range. Deals additional 10 magic damage to dark debuffed targets.",
           "Deals 121 magic damage per second for 10 seconds to targets in range. Deals additional 12 magic damage to dark debuffed targets.",
           "Deals 144 magic damage per second for 10 seconds to targets in range. Deals additional 14 magic damage to dark debuffed targets.",
           "Deals 170 magic damage per second for 10 seconds to targets in range. Deals additional 17 magic damage to dark debuffed targets.",
           "Deals 201 magic damage per second for 10 seconds to targets in range. Deals additional 20 magic damage to dark debuffed targets.",
           "Deals 233 magic damage per second for 10 seconds to targets in range. Deals additional 23 magic damage to dark debuffed targets.",
           "Deals 270 magic damage per second for 10 seconds to targets in range. Deals additional 27 magic damage to dark debuffed targets.",
           "Deals 308 magic damage per second for 10 seconds to targets in range. Deals additional 31 magic damage to dark debuffed targets."
       ],
       ["Explodes if target's HP drops below 50% or after 20 seconds. Deals 389 magic damage to all enemies in a 4 meter radius. Deals 38 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 471 magic damage to all enemies in a 4 meter radius. Deals 47 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 572 magic damage to all enemies in a 4 meter radius. Deals 57 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 691 magic damage to all enemies in a 4 meter radius. Deals 69 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 817 magic damage to all enemies in a 4 meter radius. Deals 81 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 966 magic damage to all enemies in a 4 meter radius. Deals 96 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 1126 magic damage to all enemies in a 4 meter radius. Deals 112 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 1302 magic damage to all enemies in a 4 meter radius. Deals 130 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 1494 magic damage to all enemies in a 4 meter radius. Deals 149 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 1698 magic damage to all enemies in a 4 meter radius. Deals 169 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 1906 magic damage to all enemies in a 4 meter radius. Deals 190 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 2144 magic damage to all enemies in a 4 meter radius. Deals 214 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 2402 magic damage to all enemies in a 4 meter radius. Deals 240 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 2668 magic damage to all enemies in a 4 meter radius. Deals 266 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 2965 magic damage to all enemies in a 4 meter radius. Deals 296 additional magic damage to targets under dark debuff.",
           "Explodes if target's HP drops below 50% or after 20 seconds. Deals 3292 magic damage to all enemies in a 4 meter radius. Deals 329 additional magic damage to targets under dark debuff."
       ],
       ["Deals 378 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 132 damage to lighting debuffed targets.",
           "Deals 456 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 160 damage to lighting debuffed targets.",
           "Deals 551 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 193 damage to lighting debuffed targets.",
           "Deals 651 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 228 damage to lighting debuffed targets.",
           "Deals 768 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 269 damage to lighting debuffed targets.",
           "Deals 893 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 313 damage to lighting debuffed targets.",
           "Deals 1033 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 362 damage to lighting debuffed targets.",
           "Deals 1180 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 413 damage to lighting debuffed targets.",
           "Deals 1335 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 467 damage to lighting debuffed targets.",
           "Deals 1500 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 526 damage to lighting debuffed targets.",
           "Deals 1687 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 590 damage to lighting debuffed targets.",
           "Deals 1887 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 660 damage to lighting debuffed targets.",
           "Deals 2095 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 733 damage to lighting debuffed targets.",
           "Deals 2328 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 815 damage to lighting debuffed targets.",
           "Deals 2586 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 905 damage to lighting debuffed targets.",
           "Deals 2872 magic damage and vanishes defense skills a maximum of 2 times. Deals additional 1005 damage to lighting debuffed targets."
       ],
       ["Deals 476 magic damage to enemies in range. Decreases move speed by 20 for 8 seconds. Deals additional 119 magic damage to fire debuffed targets.",
           "Deals 576 magic damage to enemies in range. Decreases move speed by 22 for 8 seconds. Deals additional 144 magic damage to fire debuffed targets.",
           "Deals 684 magic damage to enemies in range. Decreases move speed by 24 for 8 seconds. Deals additional 171 magic damage to fire debuffed targets.",
           "Deals 804 magic damage to enemies in range. Decreases move speed by 26 for 8 seconds. Deals additional 202 magic damage to fire debuffed targets.",
           "Deals 948 magic damage to enemies in range. Decreases move speed by 28 for 8 seconds. Deals additional 237 magic damage to fire debuffed targets.",
           "Deals 1096 magic damage to enemies in range. Decreases move speed by 30 for 8 seconds. Deals additional 274 magic damage to fire debuffed targets.",
           "Deals 1264 magic damage to enemies in range. Decreases move speed by 32 for 8 seconds. Deals additional 316 magic damage to fire debuffed targets.",
           "Deals 1440 magic damage to enemies in range. Decreases move speed by 34 for 8 seconds. Deals additional 360 magic damage to fire debuffed targets.",
           "Deals 1618 magic damage to enemies in range. Decreases move speed by 36 for 8 seconds. Deals additional 405 magic damage to fire debuffed targets.",
           "Deals 1818 magic damage to enemies in range. Decreases move speed by 38 for 8 seconds. Deals additional 455 magic damage to fire debuffed targets.",
           "Deals 2044 magic damage to enemies in range. Decreases move speed by 40 for 8 seconds. Deals additional 511 magic damage to fire debuffed targets.",
           "Deals 2272 magic damage to enemies in range. Decreases move speed by 42 for 8 seconds. Deals additional 568 magic damage to fire debuffed targets.",
           "Deals 2524 magic damage to enemies in range. Decreases move speed by 44 for 8 seconds. Deals additional 631 magic damage to fire debuffed targets.",
           "Deals 2804 magic damage to enemies in range. Decreases move speed by 46 for 8 seconds. Deals additional 701 magic damage to fire debuffed targets.",
           "Deals 3112 magic damage to enemies in range. Decreases move speed by 48 for 8 seconds. Deals additional 778 magic damage to fire debuffed targets.",
           "Deals 3458 magic damage to enemies in range. Decreases move speed by 50 for 8 seconds. Deals additional 865 magic damage to fire debuffed targets."
       ],
       ["Puts enemies within 5 meters to sleep for 4 seconds. This skill cannot be automatically recast.",
           "Puts enemies within 5 meters to sleep for 8 seconds. This skill cannot be automatically recast.",
           "Puts enemies within 5 meters to sleep for 12 seconds. This skill cannot be automatically recast.",
           "Puts enemies within 5 meters to sleep for 16 seconds. This skill cannot be automatically recast.",
           "Puts enemies within 5 meters to sleep for 20 seconds. This skill cannot be automatically recast.",
           "Puts enemies within 5 meters to sleep for 24 seconds. This skill cannot be automatically recast.",
           "Puts enemies within 5 meters to sleep for 28 seconds. This skill cannot be automatically recast.",
           "Puts enemies within 5 meters to sleep for 32 seconds. This skill cannot be automatically recast.",
           "Puts enemies within 5 meters to sleep for 36 seconds. This skill cannot be automatically recast.",
           "Puts enemies within 5 meters to sleep for 40 seconds. This skill cannot be automatically recast."
       ],
       ["The dark hand decreases Magic DEF by 6% and inflicts fire, dark, lighting debuff LVL 1 for 10 seconds.",
           "The dark hand decreases Magic DEF by 7% and inflicts fire, dark, lighting debuff LVL 2 for 11 seconds.",
           "The dark hand decreases Magic DEF by 8% and inflicts fire, dark, lighting debuff LVL 3 for 12 seconds.",
           "The dark hand decreases Magic DEF by 9% and inflicts fire, dark, lighting debuff LVL 4 for 13 seconds.",
           "The dark hand decreases Magic DEF by 10% and inflicts fire, dark, lighting debuff LVL 5 for 14 seconds.",
           "The dark hand decreases Magic DEF by 11% and inflicts fire, dark, lighting debuff LVL 6 for 15 seconds.",
           "The dark hand decreases Magic DEF by 12% and inflicts fire, dark, lighting debuff LVL 7 for 16 seconds.",
           "The dark hand decreases Magic DEF by 13% and inflicts fire, dark, lighting debuff LVL 8 for 17 seconds.",
           "The dark hand decreases Magic DEF by 14% and inflicts fire, dark, lighting debuff LVL 9 for 18 seconds.",
           "The dark hand decreases Magic DEF by 15% and inflicts fire, dark, lighting debuff LVL 10 for 20 seconds."
       ],
       ["Teleports to the saved location with all party members who are within 10 meters. Maximum of 1 locations can be saved.",
           "Teleports to the saved location with all party members who are within 10 meters. Maximum of 2 locations can be saved.",
           "Teleports to the saved location with all party members who are within 10 meters. Maximum of 3 locations can be saved.",
           "Teleports to the saved location with all party members who are within 10 meters. Maximum of 4 locations can be saved.",
           "Teleports to the saved location with all party members who are within 10 meters. Maximum of 5 locations can be saved.",
           "Teleports to the saved location with all party members who are within 10 meters. Maximum of 5 locations can be saved.",
           "Teleports to the saved location with all party members who are within 10 meters. Maximum of 5 locations can be saved.",
           "Teleports to the saved location with all party members who are within 10 meters. Maximum of 5 locations can be saved.",
           "Teleports to the saved location with all party members who are within 10 meters. Maximum of 5 locations can be saved.",
           "Teleports to the saved location with all party members who are within 10 meters. Maximum of 5 locations can be saved."
       ],
       ["Deals 2399 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 239 additional magic damage to targets under dark debuff.",
           "Deals 2833 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 283 additional magic damage to targets under dark debuff.",
           "Deals 3343 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 334 additional magic damage to targets under dark debuff.",
           "Deals 3884 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 388 additional magic damage to targets under dark debuff.",
           "Deals 4493 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 449 additional magic damage to targets under dark debuff.",
           "Deals 5133 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 513 additional magic damage to targets under dark debuff.",
           "Deals 5811 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 581 additional magic damage to targets under dark debuff.",
           "Deals 6527 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 652 additional magic damage to targets under dark debuff.",
           "Deals 7342 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 734 additional magic damage to targets under dark debuff.",
           "Deals 8210 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 821 additional magic damage to targets under dark debuff.",
           "Deals 9116 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 911 additional magic damage to targets under dark debuff.",
           "Deals 10129 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 1012 additional magic damage to targets under dark debuff.",
           "Deals 11249 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 1124 additional magic damage to targets under dark debuff.",
           "Deals 12384 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 1238 additional magic damage to targets under dark debuff.",
           "Deals 13633 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 1363 additional magic damage to targets under dark debuff.",
           "Deals 15011 magic damage to all enemies in a 6 meter radius and stuns for 5 seconds. Deals 1501 additional magic damage to targets under dark debuff."
       ],
       ["Deals 984 magic damage to target and 75% of inflicted damage to caster. Deals additional 197 magic damage to dark debuffed targets.",
           "Deals 1138 magic damage to target and 73% of inflicted damage to caster. Deals additional 228 magic damage to dark debuffed targets.",
           "Deals 1304 magic damage to target and 71% of inflicted damage to caster. Deals additional 261 magic damage to dark debuffed targets.",
           "Deals 1484 magic damage to target and 69% of inflicted damage to caster. Deals additional 297 magic damage to dark debuffed targets.",
           "Deals 1668 magic damage to target and 67% of inflicted damage to caster. Deals additional 334 magic damage to dark debuffed targets.",
           "Deals 1874 magic damage to target and 65% of inflicted damage to caster. Deals additional 375 magic damage to dark debuffed targets.",
           "Deals 2102 magic damage to target and 63% of inflicted damage to caster. Deals additional 420 magic damage to dark debuffed targets.",
           "Deals 2332 magic damage to target and 61% of inflicted damage to caster. Deals additional 466 magic damage to dark debuffed targets.",
           "Deals 2592 magic damage to target and 59% of inflicted damage to caster. Deals additional 518 magic damage to dark debuffed targets.",
           "Deals 2880 magic damage to target and 57% of inflicted damage to caster. Deals additional 576 magic damage to dark debuffed targets.",
           "Deals 3198 magic damage to target and 55% of inflicted damage to caster. Deals additional 640 magic damage to dark debuffed targets.",
           "Deals 3550 magic damage to target and 53% of inflicted damage to caster. Deals additional 710 magic damage to dark debuffed targets.",
           "Deals 3944 magic damage to target and 50% of inflicted damage to caster. Deals additional 789 magic damage to dark debuffed targets."
       ],
       ["Increases the probablity of resisting against silence and fear by 5% and 3% respectively.",
           "Increases the probablity of resisting against silence and fear by 10% and 6% respectively.",
           "Increases the probablity of resisting against silence and fear by 15% and 9% respectively.",
           "Increases the probablity of resisting against silence and fear by 20% and 12% respectively.",
           "Increases the probablity of resisting against silence and fear by 25% and 15% respectively.",
           "Increases the probablity of resisting against silence and fear by 30% and 18% respectively.",
           "Increases the probablity of resisting against silence and fear by 35% and 21% respectively.",
           "Increases the probablity of resisting against silence and fear by 40% and 24% respectively.",
           "Increases the probablity of resisting against silence and fear by 45% and 27% respectively.",
           "Increases the probablity of resisting against silence and fear by 50% and 30% respectively."
       ],
       ["Deals 572 magic damage per second to all enemies within target area for 12 seconds and decreases move speed by 10. Deals 57 additional magic damage to targets under dark debuff.",
           "Deals 646 magic damage per second to all enemies within target area for 12 seconds and decreases move speed by 12. Deals 64 additional magic damage to targets under dark debuff.",
           "Deals 725 magic damage per second to all enemies within target area for 12 seconds and decreases move speed by 14. Deals 72 additional magic damage to targets under dark debuff.",
           "Deals 815 magic damage per second to all enemies within target area for 12 seconds and decreases move speed by 16. Deals 81 additional magic damage to targets under dark debuff.",
           "Deals 914 magic damage per second to all enemies within target area for 12 seconds and decreases move speed by 18. Deals 91 additional magic damage to targets under dark debuff.",
           "Deals 1014 magic damage per second to all enemies within target area for 12 seconds and decreases move speed by 20. Deals 101 additional magic damage to targets under dark debuff.",
           "Deals 1128 magic damage per second to all enemies within target area for 12 seconds and decreases move speed by 22. Deals 112 additional magic damage to targets under dark debuff.",
           "Deals 1252 magic damage per second to all enemies within target area for 12 seconds and decreases move speed by 24. Deals 125 additional magic damage to targets under dark debuff.",
           "Deals 1390 magic damage per second to all enemies within target area for 12 seconds and decreases move speed by 26. Deals 139 additional magic damage to targets under dark debuff.",
           "Deals 1544 magic damage per second to all enemies within target area for 12 seconds and decreases move speed by 28. Deals 154 additional magic damage to targets under dark debuff.",
           "Deals 1715 magic damage per second to all enemies within target area for 12 seconds and decreases move speed by 30. Deals 171 additional magic damage to targets under dark debuff."
       ],
       ["Summon a blazing flame pillar to deal 1678 magical damage to an enemy and its surroundings within a 4m radius and Shock them for 3sec. Adds additional 553 damage when Shock ends and 420 magical damage to enemies in Flame acceleration state.",
           "Summon a blazing flame pillar to deal 1886 magical damage to an enemy and its surroundings within a 4m radius and Shock them for 3sec. Adds additional 622 damage when Shock ends and 472 magical damage to enemies in Flame acceleration state.",
           "Summon a blazing flame pillar to deal 2122 magical damage to an enemy and its surroundings within a 4m radius and Shock them for 3sec. Adds additional 700 damage when Shock ends and 531 magical damage to enemies in Flame acceleration state.",
           "Summon a blazing flame pillar to deal 2386 magical damage to an enemy and its surroundings within a 4m radius and Shock them for 3sec. Adds additional 787 damage when Shock ends and 597 magical damage to enemies in Flame acceleration state.",
           "Summon a blazing flame pillar to deal 2657 magical damage to an enemy and its surroundings within a 4m radius and Shock them for 3sec. Adds additional 876 damage when Shock ends and 664 magical damage to enemies in Flame acceleration state.",
           "Summon a blazing flame pillar to deal 2950 magical damage to an enemy and its surroundings within a 4m radius and Shock them for 3sec. Adds additional 973 damage when Shock ends and 738 magical damage to enemies in Flame acceleration state.",
           "Summon a blazing flame pillar to deal 3276 magical damage to an enemy and its surroundings within a 4m radius and Shock them for 3sec. Adds additional 1081 damage when Shock ends and 819 magical damage to enemies in Flame acceleration state.",
           "Summon a blazing flame pillar to deal 3638 magical damage to an enemy and its surroundings within a 4m radius and Shock them for 3sec. Adds additional 1200 damage when Shock ends and 910 magical damage to enemies in Flame acceleration state.",
           "Summon a blazing flame pillar to deal 4042 magical damage to an enemy and its surroundings within a 4m radius and Shock them for 3sec. Adds additional 1333 damage when Shock ends and 1011 magical damage to enemies in Flame acceleration state.",
           "Summon a blazing flame pillar to deal 4490 magical damage to an enemy and its surroundings within a 4m radius and Shock them for 3sec. Adds additional 1481 damage when Shock ends and 1123 magical damage to enemies in Flame acceleration state.",
           "Summon a blazing flame pillar to deal 4730 magical damage to an enemy and its surroundings within a 4m radius and Shock them for 3sec. Adds additional 1560 damage when Shock ends and 1183 magical damage to enemies in Flame acceleration state."
       ],
       ["Decreases your chance to be interrupted by any attack by 4% and decreases mana consumption by 5%",
           "Decreases your chance to be interrupted by any attack by 8% and decreases mana consumption by 6%",
           "Decreases your chance to be interrupted by any attack by 12% and decreases mana consumption by 7%",
           "Decreases your chance to be interrupted by any attack by 16% and decreases mana consumption by 8%",
           "Decreases your chance to be interrupted by any attack by 20% and decreases mana consumption by 9%",
           "Decreases your chance to be interrupted by any attack by 24% and decreases mana consumption by 10%",
           "Decreases your chance to be interrupted by any attack by 28% and decreases mana consumption by 11%",
           "Decreases your chance to be interrupted by any attack by 32% and decreases mana consumption by 12%",
           "Decreases your chance to be interrupted by any attack by 36% and decreases mana consumption by 13%",
           "Decreases your chance to be interrupted by any attack by 40% and decreases mana consumption by 15%"
       ],
       ["Deals 884 damage to enemies in range 5 times. Decreases move speed and vanishes protect buffs 3 times. Deals additional 159 damage to lighting debuffed targets.",
           "Deals 994 damage to enemies in range 5 times. Decreases move speed and vanishes protect buffs 3 times. Deals additional 179 damage to lighting debuffed targets.",
           "Deals 1107 damage to enemies in range 5 times. Decreases move speed and vanishes protect buffs 3 times. Deals additional 199 damage to lighting debuffed targets.",
           "Deals 1229 damage to enemies in range 5 times. Decreases move speed and vanishes protect buffs 3 times. Deals additional 221 damage to lighting debuffed targets.",
           "Deals 1365 damage to enemies in range 5 times. Decreases move speed and vanishes protect buffs 3 times. Deals additional 246 damage to lighting debuffed targets.",
           "Deals 1516 damage to enemies in range 5 times. Decreases move speed and vanishes protect buffs 3 times. Deals additional 273 damage to lighting debuffed targets.",
           "Deals 1684 damage to enemies in range 5 times. Decreases move speed and vanishes protect buffs 3 times. Deals additional 303 damage to lighting debuffed targets.",
           "Deals 1871 damage to enemies in range 5 times. Decreases move speed and vanishes protect buffs 3 times. Deals additional 337 damage to lighting debuffed targets.",
           "Deals 1971 damage to enemies in range 5 times. Decreases move speed and vanishes protect buffs 3 times. Deals additional 355 damage to lighting debuffed targets."
       ],
       ["Absorbs 8848 Physical Attack for 120 secs and increases max skill attack by 890, Critical Rate by 25 and Dodge Rate by 31. Absorbs 25% Physical damage received from a wide range attack. It deactivates if max absorb value is reached.",
           "Absorbs 9919 Physical Attack for 120 secs and increases max skill attack by 997, Critical Rate by 28 and Dodge Rate by 33. Absorbs 25% Physical damage received from a wide range attack. It deactivates if max absorb value is reached.",
           "Absorbs 11018 Physical Attack for 120 secs and increases max skill attack by 1107, Critical Rate by 31 and Dodge Rate by 35. Absorbs 25% Physical damage received from a wide range attack. It deactivates if max absorb value is reached.",
           "Absorbs 12243 Physical Attack for 120 secs and increases max skill attack by 1231, Critical Rate by 34 and Dodge Rate by 37. Absorbs 25% Physical damage received from a wide range attack. It deactivates if max absorb value is reached.",
           "Absorbs 13601 Physical Attack for 120 secs and increases max skill attack by 1367, Critical Rate by 37 and Dodge Rate by 39. Absorbs 25% Physical damage received from a wide range attack. It deactivates if max absorb value is reached.",
           "Absorbs 15099 Physical Attack for 120 secs and increases max skill attack by 1518, Critical Rate by 40 and Dodge Rate by 41. Absorbs 25% Physical damage received from a wide range attack. It deactivates if max absorb value is reached.",
           "Absorbs 16765 Physical Attack for 120 secs and increases max skill attack by 1686, Critical Rate by 43 and Dodge Rate by 43. Absorbs 25% Physical damage received from a wide range attack. It deactivates if max absorb value is reached.",
           "Absorbs 18620 Physical Attack for 120 secs and increases max skill attack by 1872, Critical Rate by 46 and Dodge Rate by 45. Absorbs 25% Physical damage received from a wide range attack. It deactivates if max absorb value is reached."
       ],
       ["Causes explosion on the selected area and deals 2940 nagic Attack. Decreases max of 3675 Mana and deals equivalent additional Damage. Deals Additional 661 Magic Attack to targets under dark debuff.",
           "Causes explosion on the selected area and deals 3265 nagic Attack. Decreases max of 4081 Mana and deals equivalent additional Damage. Deals Additional 734 Magic Attack to targets under dark debuff.",
           "Causes explosion on the selected area and deals 3629 nagic Attack. Decreases max of 4536 Mana and deals equivalent additional Damage. Deals Additional 816 Magic Attack to targets under dark debuff.",
           "Causes explosion on the selected area and deals 4029 nagic Attack. Decreases max of 5037 Mana and deals equivalent additional Damage. Deals Additional 906 Magic Attack to targets under dark debuff.",
           "Causes explosion on the selected area and deals 4474 nagic Attack. Decreases max of 5593 Mana and deals equivalent additional Damage. Deals Additional 1006 Magic Attack to targets under dark debuff.",
           "Causes explosion on the selected area and deals 4970 nagic Attack. Decreases max of 6213 Mana and deals equivalent additional Damage. Deals Additional 1118 Magic Attack to targets under dark debuff.",
           "Causes explosion on the selected area and deals 5519 nagic Attack. Decreases max of 6899 Mana and deals equivalent additional Damage. Deals Additional 1241 Magic Attack to targets under dark debuff."
       ],
       ["Deals 2099 Magic Attack to target and nearby enemies within 3 M. Increases magic damage received by taget by 20% for 3 secs. Deals additional 378 magic damage to target under electric debuff and removes mult. defense skills 2 times.",
           "Deals 2333 Magic Attack to target and nearby enemies within 3 M. Increases magic damage received by taget by 22% for 3 secs. Deals additional 420 magic damage to target under electric debuff and removes mult. defense skills 2 times.",
           "Deals 2590 Magic Attack to target and nearby enemies within 3 M. Increases magic damage received by taget by 24% for 3 secs. Deals additional 466 magic damage to target under electric debuff and removes mult. defense skills 2 times.",
           "Deals 2876 Magic Attack to target and nearby enemies within 3 M. Increases magic damage received by taget by 26% for 3 secs. Deals additional 518 magic damage to target under electric debuff and removes mult. defense skills 2 times.",
           "Deals 3195 Magic Attack to target and nearby enemies within 3 M. Increases magic damage received by taget by 28% for 3 secs. Deals additional 575 magic damage to target under electric debuff and removes mult. defense skills 2 times.",
           "Deals 3548 Magic Attack to target and nearby enemies within 3 M. Increases magic damage received by taget by 30% for 3 secs. Deals additional 639 magic damage to target under electric debuff and removes mult. defense skills 2 times."
       ],
       ["Sends crystalized mana into your target, dealing 2151 magical damage plus an additional damage of 5% current mana",
           "Sends crystalized mana into your target, dealing 2389 magical damage plus an additional damage of 6% current mana",
           "Sends crystalized mana into your target, dealing 2653 magical damage plus an additional damage of 7% current mana",
           "Sends crystalized mana into your target, dealing 2947 magical damage plus an additional damage of 8% current mana",
           "Sends crystalized mana into your target, dealing 3274 magical damage plus an additional damage of 9% current mana"
       ],
       ["Conjure an icy tornado around the user to deal 2948 magical damage to enemies within a 5m radius and stun them for 3 sec.",
           "Conjure an icy tornado around the user to deal 3276 magical damage to enemies within a 5m radius and stun them for 4 sec.",
           "Conjure an icy tornado around the user to deal 3637 magical damage to enemies within a 5m radius and stun them for 5 sec.",
           "Conjure an icy tornado around the user to deal 4041 magical damage to enemies within a 5m radius and stun them for 6 sec.",
           "Conjure an icy tornado around the user to deal 4257 magical damage to enemies within a 5m radius and stun them for 7 sec."
       ],
       ["Summon a shadowy gale to Shock enemies and coat the user with a DEF boosting Black Shroud. When the Shock state ends, enemies receive 6064 damage.",
           "Summon a shadowy gale to Shock enemies and coat the user with a DEF boosting Black Shroud. When the Shock state ends, enemies receive 6736 damage.",
           "Summon a shadowy gale to Shock enemies and coat the user with a DEF boosting Black Shroud. When the Shock state ends, enemies receive 7484 damage.",
           "Summon a shadowy gale to Shock enemies and coat the user with a DEF boosting Black Shroud. When the Shock state ends, enemies receive 7884 damage."
       ],
       ["The Abyssal Gate opened within 6m radius of a targeted point inflicts 3453 magical damage per seconds for 8 seconds and decreases Movement Speed(can't be cancelled). By responding all debuff states, adds 132 magical damage per debuff level.",
           "The Abyssal Gate opened within 6m radius of a targeted point inflicts 3834 magical damage per seconds for 8 seconds and decreases Movement Speed(can't be cancelled). By responding all debuff states, adds 158 magical damage per debuff level."
       ]
   ],
   cd: [
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60],
       [40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25],
       [60, 58, 56, 54, 52, 50, 48, 46, 44, 40],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15],
       [120, 120, 120, 120, 120, 120, 120, 120, 120, 120],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [600, 600, 600, 600, 600, 480, 360, 240, 120, 60],
       [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180],
       [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [300, 300, 300, 300, 300, 300, 300, 300, 300],
       [60, 60, 60, 60, 60, 60, 60, 60],
       [120, 120, 120, 120, 120, 120, 120],
       [6, 6, 6, 6, 6, 6],
       [12, 12, 12, 12, 12],
       [90, 90, 90, 90, 90],
       [106, 104, 102, 100],
       [110, 110]
   ],
   mp: [
       [47, 59, 79, 101, 125, 155, 188, 228, 277, 335, 403, 476, 562, 653, 755, 869],
       [119, 160, 203, 251, 311, 378, 456, 554, 670, 807, 953, 1126, 1310, 1516, 1731, 1958],
       [54, 70, 88, 109, 134, 162, 196, 238, 288, 342],
       [66, 83, 103, 127, 154, 187, 227, 274, 330, 390, 461, 535, 619, 712, 800, 899],
       [178, 222, 273, 355, 425, 508, 611, 733, 916, 1070, 1318, 1509, 1732, 1994, 2219, 2466],
       [122, 153, 188, 228, 276, 335, 405, 489, 576, 681, 790, 914, 1052, 1182, 1328, 1494],
       [109, 134, 161, 195, 237, 288, 243, 404, 476, 551],
       [96, 116, 141, 171, 208, 250, 296, 350, 408, 472, 546, 615, 691, 777, 871, 967],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [407, 494, 599, 726, 866, 1022, 1207, 1397, 1618, 1846],
       [292, 353, 429, 518, 613, 725, 845, 977, 1121, 1274, 1430, 1608, 1802, 2001, 2224, 2469],
       [359, 433, 523, 617, 728, 846, 979, 1127, 1266, 1422, 1599, 1789, 1986, 2206, 2451, 2722],
       [357, 432, 513, 605, 711, 822, 954, 1080, 1214, 1364, 1533, 1704, 1893, 2103, 2334, 2594],
       [561, 677, 798, 942, 1094, 1266, 1455, 1635, 1838, 2067],
       [501, 595, 701, 824, 953, 1098, 1251, 1406, 1579, 1776],
       [1697, 1982, 2317, 2820, 3232, 3779, 4203, 4675, 5203, 5909],
       [1799, 2125, 2507, 2913, 3370, 3850, 4358, 4895, 5507, 6158, 6837, 7597, 8437, 9288, 10225, 11258],
       [168, 194, 222, 253, 284, 319, 357, 397, 441, 490, 544, 604, 671],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4633, 5233, 5873, 6602, 7403, 8213, 9137, 10141, 11259, 12506, 13892],
       [1259, 1415, 1592, 1790, 1993, 2213, 2457, 2729, 3032, 3368, 3548],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4551, 5103, 5757, 6369, 7053, 7809, 8817, 9795, 10320],
       [3893, 4364, 4847, 5386, 5984, 6643, 7376, 8192],
       [2205, 2449, 2722, 3022, 3356, 3728, 4139],
       [2361, 2625, 2914, 3236, 3594, 3992],
       [1613, 1792, 1990, 2210, 2456],
       [2064, 2293, 2546, 2829, 2980],
       [3153, 3503, 3892, 4100],
       [3911, 4345]
   ],
   cast: [
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [6, 6, 6, 6, 6, 6, 6, 6, 6],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0]
   ],
   skillLevel: [
       [1, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60],
       [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64],
       [6, 10, 14, 18, 22, 26, 30, 34, 38, 42],
       [8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68],
       [10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70],
       [12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72],
       [17, 21, 25, 29, 33, 37, 41, 45, 49, 53],
       [19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67, 71, 75, 79],
       [21, 25, 29, 33, 37, 41, 45, 49, 53, 57],
       [23, 27, 31, 35, 39, 43, 47, 51, 55, 59],
       [25, 29, 33, 37, 41, 45, 49, 53, 57, 61],
       [27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67, 71, 75, 79, 83, 87],
       [32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92],
       [34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74, 78, 82, 86, 90, 94],
       [36, 40, 44, 48, 52, 56, 60, 64, 68, 72],
       [38, 42, 46, 50, 54, 58, 62, 66, 70, 74],
       [40, 44, 48, 52, 56, 60, 64, 68, 72, 76],
       [40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 99],
       [51, 55, 59, 63, 67, 71, 75, 79, 83, 87, 91, 95, 99],
       [55, 59, 63, 67, 71, 75, 79, 83, 87, 91],
       [59, 63, 67, 71, 75, 79, 83, 87, 91, 95, 99],
       [61, 65, 69, 73, 77, 81, 85, 89, 93, 97, 99],
       [65, 69, 73, 77, 81, 85, 89, 93, 97, 99],
       [69, 73, 77, 81, 85, 89, 93, 97, 99],
       [71, 75, 79, 83, 87, 91, 95, 99],
       [75, 79, 83, 87, 91, 95, 99],
       [79, 83, 87, 91, 95, 99],
       [81, 85, 89, 93, 97],
       [85, 89, 93, 97, 99],
       [89, 93, 97, 99],
       [95, 99]
   ]

};