var Warrior = {
   skillDescription: ["Slash", "Charge", "Armor Break", "Taunt", "Berserk", "Blade Storm", "Howl of Glory", "Smash", "Focused Might", "Dragon Spirit", "Howl of Valor", "Earthquake", "Howl of Wrath", "Lionheart",
       "Gash", "Howl of Fortitude", "Dragon Strike", "Shockwave", "Howl of Dread", "Battle inspiration", "Dragon Rage", "Deadly Charge", "Battle Instinct", "Master of Blades", "Blood Strike", "Howl of Freedom",
       "Howl of Blood", "Masochism", "Power Stark", "Brutal Edge", "Last Stand"
   ],
   skillInfo: [
       ["Strongly slays an enemy and inflicts 33 physical damage.",
           "Strongly slays an enemy and inflicts 39 physical damage.",
           "Strongly slays an enemy and inflicts 53 physical damage.",
           "Strongly slays an enemy and inflicts 69 physical damage.",
           "Strongly slays an enemy and inflicts 85 physical damage.",
           "Strongly slays an enemy and inflicts 105 physical damage.",
           "Strongly slays an enemy and inflicts 127 physical damage.",
           "Strongly slays an enemy and inflicts 155 physical damage.",
           "Strongly slays an enemy and inflicts 188 physical damage.",
           "Strongly slays an enemy and inflicts 228 physical damage.",
           "Strongly slays an enemy and inflicts 275 physical damage.",
           "Strongly slays an enemy and inflicts 325 physical damage.",
           "Strongly slays an enemy and inflicts 383 physical damage.",
           "Strongly slays an enemy and inflicts 444 physical damage.",
           "Strongly slays an enemy and inflicts 515 physical damage.",
           "Strongly slays an enemy and inflicts 592 physical damage."
       ],
       ["Charges 8 meters. Deals 13 physical change. Stuns for 3 seconds.",
           "Charges 8 meters. Deals 17 physical change. Stuns for 3 seconds.",
           "Charges 9 meters. Deals 22 physical change. Stuns for 3 seconds.",
           "Charges 9 meters. Deals 27 physical change. Stuns for 3 seconds.",
           "Charges 10 meters. Deals 34 physical change. Stuns for 3 seconds.",
           "Charges 10 meters. Deals 41 physical change. Stuns for 3 seconds.",
           "Charges 11 meters. Deals 50 physical change. Stuns for 3 seconds.",
           "Charges 11 meters. Deals 60 physical change. Stuns for 3 seconds.",
           "Charges 12 meters. Deals 73 physical change. Stuns for 3 seconds.",
           "Charges 12 meters. Deals 88 physical change. Stuns for 3 seconds.",
           "Charges 12 meters. Deals 88 physical change. Stuns for 3 seconds."
       ],
       ["Inflicts 62 physical damage and for 12 seconds, it decreases physical DEF by 100",
           "Inflicts 80 physical damage and for 12 seconds, it decreases physical DEF by 131",
           "Inflicts 101 physical damage and for 12 seconds, it decreases physical DEF by 164",
           "Inflicts 124 physical damage and for 12 seconds, it decreases physical DEF by 203",
           "Inflicts 152 physical damage and for 12 seconds, it decreases physical DEF by 258",
           "Inflicts 185 physical damage and for 12 seconds, it decreases physical DEF by 319",
           "Inflicts 225 physical damage and for 12 seconds, it decreases physical DEF by 385",
           "Inflicts 272 physical damage and for 12 seconds, it decreases physical DEF by 467",
           "Inflicts 330 physical damage and for 12 seconds, it decreases physical DEF by 566",
           "Inflicts 391 physical damage and for 12 seconds, it decreases physical DEF by 671",
           "Inflicts 461 physical damage and for 12 seconds, it decreases physical DEF by 792",
           "Inflicts 542 physical damage and for 12 seconds, it decreases physical DEF by 946",
           "Inflicts 628 physical damage and for 12 seconds, it decreases physical DEF by 1120",
           "Inflicts 725 physical damage and for 12 seconds, it decreases physical DEF by 1299",
           "Inflicts 824 physical damage and for 12 seconds, it decreases physical DEF by 1484",
           "Inflicts 927 physical damage and for 12 seconds, it decreases physical DEF by 1672"
       ],
       ["Increases threat level by 1 and focuses the target's attention on you for 3 seconds.",
           "Increases threat level by 2 and focuses the target's attention on you for 3 seconds.",
           "Increases threat level by 3 and focuses the target's attention on you for 3 seconds.",
           "Increases threat level by 4 and focuses the target's attention on you for 3 seconds.",
           "Increases threat level by 5 and focuses the target's attention on you for 4 seconds.",
           "Increases threat level by 6 and focuses the target's attention on you for 4 seconds.",
           "Increases threat level by 7 and focuses the target's attention on you for 4 seconds.",
           "Increases threat level by 8 and focuses the target's attention on you for 4 seconds.",
           "Increases threat level by 9 and focuses the target's attention on you for 5 seconds.",
           "Increases threat level by 10 and focuses the target's attention on you for 5 seconds.",
           "Increases threat level by 11 and focuses the target's attention on you for 5 seconds.",
           "Increases threat level by 12 and focuses the target's attention on you for 5 seconds.",
           "Increases threat level by 13 and focuses the target's attention on you for 6 seconds.",
           "Increases threat level by 14 and focuses the target's attention on you for 6 seconds.",
           "Increases threat level by 15 and focuses the target's attention on you for 6 seconds.",
           "Increases threat level by 16 and focuses the target's attention on you for 6 seconds."
       ],
       ["Increases attack by 13 and move speed by 3. Decreases dodge rate by 1.",
           "Increases attack by 15 and move speed by 3. Decreases dodge rate by 1.",
           "Increases attack by 18 and move speed by 4. Decreases dodge rate by 2.",
           "Increases attack by 22 and move speed by 4. Decreases dodge rate by 2.",
           "Increases attack by 26 and move speed by 5. Decreases dodge rate by 3.",
           "Increases attack by 31 and move speed by 5. Decreases dodge rate by 3.",
           "Increases attack by 36 and move speed by 6. Decreases dodge rate by 4.",
           "Increases attack by 41 and move speed by 6. Decreases dodge rate by 4.",
           "Increases attack by 48 and move speed by 7. Decreases dodge rate by 5.",
           "Increases attack by 56 and move speed by 7. Decreases dodge rate by 5.",
           "Increases attack by 64 and move speed by 8. Decreases dodge rate by 6.",
           "Increases attack by 72 and move speed by 8. Decreases dodge rate by 6."
       ],
       ["Deals 152 physical damage to all enemies within 4 meters.",
           "Deals 191 physical damage to all enemies within 4 meters.",
           "Deals 234 physical damage to all enemies within 4 meters.",
           "Deals 283 physical damage to all enemies within 4 meters.",
           "Deals 343 physical damage to all enemies within 4 meters.",
           "Deals 415 physical damage to all enemies within 4 meters.",
           "Deals 504 physical damage to all enemies within 4 meters.",
           "Deals 600 physical damage to all enemies within 4 meters.",
           "Deals 709 physical damage to all enemies within 4 meters.",
           "Deals 837 physical damage to all enemies within 4 meters.",
           "Deals 969 physical damage to all enemies within 4 meters.",
           "Deals 1121 physical damage to all enemies within 4 meters.",
           "Deals 1279 physical damage to all enemies within 4 meters.",
           "Deals 1437 physical damage to all enemies within 4 meters.",
           "Deals 1618 physical damage to all enemies within 4 meters.",
           "Deals 1819 physical damage to all enemies within 4 meters."
       ],
       ["Increases party's Max HP by 215 and Max MP by 107; also increases HP recovery by 56 and MP recovery by 28 for 10 minutes.",
           "Increases party's Max HP by 262 and Max MP by 131; also increases HP recovery by 67 and MP recovery by 34 for 10 minutes.",
           "Increases party's Max HP by 313 and Max MP by 156; also increases HP recovery by 81 and MP recovery by 41 for 10 minutes.",
           "Increases party's Max HP by 376 and Max MP by 188; also increases HP recovery by 98 and MP recovery by 49 for 10 minutes.",
           "Increases party's Max HP by 452 and Max MP by 226; also increases HP recovery by 119 and MP recovery by 60 for 10 minutes.",
           "Increases party's Max HP by 542 and Max MP by 271; also increases HP recovery by 141 and MP recovery by 71 for 10 minutes.",
           "Increases party's Max HP by 640 and Max MP by 320; also increases HP recovery by 166 and MP recovery by 83 for 10 minutes.",
           "Increases party's Max HP by 748 and Max MP by 374; also increases HP recovery by 195 and MP recovery by 97 for 10 minutes.",
           "Increases party's Max HP by 873 and Max MP by 436; also increases HP recovery by 225 and MP recovery by 112 for 10 minutes.",
           "Increases party's Max HP by 1000 and Max MP by 500; also increases HP recovery by 257 and MP recovery by 128 for 10 minutes.",
           "Increases party's Max HP by 1148 and Max MP by 573; also increases HP recovery by 292 and MP recovery by 146 for 10 minutes.",
           "Increases party's Max HP by 1295 and Max MP by 646; also increases HP recovery by 331 and MP recovery by 166 for 10 minutes.",
           "Increases party's Max HP by 1441 and Max MP by 720; also increases HP recovery by 372 and MP recovery by 187 for 10 minutes.",
           "Increases party's Max HP by 1604 and Max MP by 802; also increases HP recovery by 414 and MP recovery by 208 for 10 minutes.",
           "Increases party's Max HP by 1784 and Max MP by 892; also increases HP recovery by 461 and MP recovery by 231 for 10 minutes.",
           "Increases party's Max HP by 1967 and Max MP by 983; also increases HP recovery by 513 and MP recovery by 257 for 10 minutes."
       ],
       ["Deals 48 physical damage and knocks back the enemy a maximum of 1 time.",
           "Deals 59 physical damage and knocks back the enemy a maximum of 1 time.",
           "Deals 71 physical damage and knocks back the enemy a maximum of 2 time.",
           "Deals 86 physical damage and knocks back the enemy a maximum of 2 time.",
           "Deals 104 physical damage and knocks back the enemy a maximum of 3 time.",
           "Deals 126 physical damage and knocks back the enemy a maximum of 3 time.",
           "Deals 149 physical damage and knocks back the enemy a maximum of 4 time.",
           "Deals 176 physical damage and knocks back the enemy a maximum of 4 time.",
           "Deals 205 physical damage and knocks back the enemy a maximum of 5 time.",
           "Deals 237 physical damage and knocks back the enemy a maximum of 5 time."
       ],
       ["Increases physical attack by 4 and hit rate by 2.",
           "Increases physical attack by 8 and hit rate by 4.",
           "Increases physical attack by 12 and hit rate by 6.",
           "Increases physical attack by 16 and hit rate by 8.",
           "Increases physical attack by 20 and hit rate by 10.",
           "Increases physical attack by 24 and hit rate by 12.",
           "Increases physical attack by 28 and hit rate by 14.",
           "Increases physical attack by 32 and hit rate by 16.",
           "Increases physical attack by 36 and hit rate by 18.",
           "Increases physical attack by 40 and hit rate by 20."
       ],
       ["Increases Max HP by 145 and recovers HP equivalent to 5% of HP recovery rate every 8 seconds during combat.",
           "Increases Max HP by 290 and recovers HP equivalent to 10% of HP recovery rate every 8 seconds during combat.",
           "Increases Max HP by 435 and recovers HP equivalent to 15% of HP recovery rate every 8 seconds during combat.",
           "Increases Max HP by 580 and recovers HP equivalent to 20% of HP recovery rate every 8 seconds during combat.",
           "Increases Max HP by 725 and recovers HP equivalent to 25% of HP recovery rate every 8 seconds during combat.",
           "Increases Max HP by 870 and recovers HP equivalent to 30% of HP recovery rate every 8 seconds during combat.",
           "Increases Max HP by 1015 and recovers HP equivalent to 35% of HP recovery rate every 8 seconds during combat.",
           "Increases Max HP by 1160 and recovers HP equivalent to 40% of HP recovery rate every 8 seconds during combat.",
           "Increases Max HP by 1305 and recovers HP equivalent to 45% of HP recovery rate every 8 seconds during combat.",
           "Increases Max HP by 1450 and recovers HP equivalent to 50% of HP recovery rate every 8 seconds during combat."
       ],
       ["Increases your party's STR, DEX and INT by 3 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 6 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 9 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 12 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 15 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 18 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 21 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 24 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 27 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 30 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 33 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 36 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 39 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 42 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 45 for 10 minutes.",
           "Increases your party's STR, DEX and INT by 48 for 10 minutes."
       ],
       ["Deals 214 physical damage to all enemies within 5 meters and lowers their move speed by 20 for 6 seconds.",
           "Deals 257 physical damage to all enemies within 5 meters and lowers their move speed by 22 for 6 seconds.",
           "Deals 313 physical damage to all enemies within 5 meters and lowers their move speed by 24 for 6 seconds.",
           "Deals 378 physical damage to all enemies within 5 meters and lowers their move speed by 26 for 6 seconds.",
           "Deals 446 physical damage to all enemies within 5 meters and lowers their move speed by 28 for 6 seconds.",
           "Deals 527 physical damage to all enemies within 5 meters and lowers their move speed by 30 for 6 seconds.",
           "Deals 614 physical damage to all enemies within 5 meters and lowers their move speed by 32 for 6 seconds.",
           "Deals 711 physical damage to all enemies within 5 meters and lowers their move speed by 34 for 6 seconds.",
           "Deals 814 physical damage to all enemies within 5 meters and lowers their move speed by 36 for 6 seconds.",
           "Deals 927 physical damage to all enemies within 5 meters and lowers their move speed by 38 for 6 seconds.",
           "Deals 1042 physical damage to all enemies within 5 meters and lowers their move speed by 40 for 6 seconds.",
           "Deals 1170 physical damage to all enemies within 5 meters and lowers their move speed by 42 for 6 seconds.",
           "Deals 1312 physical damage to all enemies within 5 meters and lowers their move speed by 44 for 6 seconds.",
           "Deals 1458 physical damage to all enemies within 5 meters and lowers their move speed by 46 for 6 seconds.",
           "Deals 1620 physical damage to all enemies within 5 meters and lowers their move speed by 48 for 6 seconds.",
           "Deals 1800 physical damage to all enemies within 5 meters and lowers their move speed by 50 for 6 seconds."
       ],
       ["Deals 240 physical damage to enemies within 6 meters and stuns them for 1 seconds.",
           "Deals 290 physical damage to enemies within 6 meters and stuns them for 1 seconds.",
           "Deals 350 physical damage to enemies within 6 meters and stuns them for 2 seconds.",
           "Deals 414 physical damage to enemies within 6 meters and stuns them for 2 seconds.",
           "Deals 488 physical damage to enemies within 6 meters and stuns them for 3 seconds.",
           "Deals 566 physical damage to enemies within 6 meters and stuns them for 3 seconds.",
           "Deals 656 physical damage to enemies within 6 meters and stuns them for 4 seconds.",
           "Deals 750 physical damage to enemies within 6 meters and stuns them for 4 seconds.",
           "Deals 848 physical damage to enemies within 6 meters and stuns them for 5 seconds.",
           "Deals 952 physical damage to enemies within 6 meters and stuns them for 5 seconds."
       ],
       ["Used when in a berserk state(Level 1+). Increase skill attack by 132 and critical rate by 5.",
           "Used when in a berserk state(Level 2+). Increase skill attack by 160 and critical rate by 6.",
           "Used when in a berserk state(Level 3+). Increase skill attack by 190 and critical rate by 7.",
           "Used when in a berserk state(Level 4+). Increase skill attack by 224 and critical rate by 8.",
           "Used when in a berserk state(Level 5+). Increase skill attack by 263 and critical rate by 9.",
           "Used when in a berserk state(Level 6+). Increase skill attack by 305 and critical rate by 10.",
           "Once triggered when Berserk(LVL 7 and up) is activated, it cancels one debuff, recovers 3% of Max HP per sec for 10 seconds, and increases a chance of resisting Movement Speed decrease and Immobilization by 41%.",
           "Once triggered when Berserk(LVL 8 and up) is activated, it cancels one debuff, recovers 3% of Max HP per sec for 10 seconds, and increases a chance of resisting Movement Speed decrease and Immobilization by 44%.",
           "Once triggered when Berserk(LVL 9 and up) is activated, it cancels one debuff, recovers 4% of Max HP per sec for 10 seconds, and increases a chance of resisting Movement Speed decrease and Immobilization by 47%.",
           "Once triggered when Berserk(LVL 10) is activated, it cancels one debuff, recovers 4% of Max HP per sec for 10 seconds, and increases a chance of resisting Movement Speed decrease and Immobilization by 50%."
       ],
       ["Deals 57 physical damage per second for 6 seconds and decreases healing target receives by 50%",
           "Deals 69 physical damage per second for 6 seconds and decreases healing target receives by 53%",
           "Deals 83 physical damage per second for 6 seconds and decreases healing target receives by 56%",
           "Deals 101 physical damage per second for 6 seconds and decreases healing target receives by 59%",
           "Deals 122 physical damage per second for 6 seconds and decreases healing target receives by 62%",
           "By making an enemy bleed, inflicts 292 physical damage per sec for 6 seconds and decreases regeneration by 70%.",
           "By making an enemy bleed, inflicts 344 physical damage per sec for 6 seconds and decreases regeneration by 72%.",
           "By making an enemy bleed, inflicts 406 physical damage per sec for 6 seconds and decreases regeneration by 74%.",
           "By making an enemy bleed, inflicts 470 physical damage per sec for 6 seconds and decreases regeneration by 76%.",
           "By making an enemy bleed, cancels one buff; inflicts 544 physical damage per sec for 6 seconds and decreases regeneration by 78%.",
           "By making an enemy bleed, cancels one buff; inflicts 620 physical damage per sec for 6 seconds and decreases regeneration by 80%.",
           "By making an enemy bleed, cancels one buff; inflicts 698 physical damage per sec for 6 seconds and decreases regeneration by 82%.",
           "By making an enemy bleed, cancels one buff; inflicts 786 physical damage per sec for 6 seconds and decreases regeneration by 84%.",
           "By making an enemy bleed, cancels one buff; inflicts 884 physical damage per sec for 6 seconds and decreases regeneration by 86%.",
           "By making an enemy bleed, cancels one buff; inflicts 984 physical damage per sec for 6 seconds and decreases regeneration by 88%.",
           "By making an enemy bleed, cancels two buffs; inflicts 1092 physical damage per sec for 6 seconds and decreases regeneration by 90%."
       ],
       ["Increases your party's physical defense by 131 and magic defense by 99. Also increases abnormal status resistance by 2 for 10 minutes.",
           "Increases your party's physical defense by 155 and magic defense by 117. Also increases abnormal status resistance by 2 for 10 minutes.",
           "Increases your party's physical defense by 183 and magic defense by 138. Also increases abnormal status resistance by 3 for 10 minutes.",
           "Increases your party's physical defense by 219 and magic defense by 165. Also increases abnormal status resistance by 3 for 10 minutes.",
           "Increases your party's physical defense by 259 and magic defense by 196. Also increases abnormal status resistance by 4 for 10 minutes.",
           "Increases your party's physical defense by 300 and magic defense by 228. Also increases abnormal status resistance by 4 for 10 minutes.",
           "Increases your party's physical defense by 343 and magic defense by 260. Also increases abnormal status resistance by 5 for 10 minutes.",
           "Increases your party's physical defense by 386 and magic defense by 295. Also increases abnormal status resistance by 5 for 10 minutes.",
           "Increases your party's physical defense by 433 and magic defense by 331. Also increases abnormal status resistance by 6 for 10 minutes.",
           "Increases your party's physical defense by 487 and magic defense by 373. Also increases abnormal status resistance by 6 for 10 minutes.",
           "Increases your party's physical defense by 550 and magic defense by 422. Also increases abnormal status resistance by 7 for 10 minutes.",
           "Increases your party's physical defense by 620 and magic defense by 476. Also increases abnormal status resistance by 7 for 10 minutes.",
           "Increases your party's physical defense by 701 and magic defense by 541. Also increases abnormal status resistance by 8 for 10 minutes.",
           "Increases your party's physical defense by 791 and magic defense by 611. Also increases abnormal status resistance by 8 for 10 minutes.",
           "Increases your party's physical defense by 892 and magic defense by 689. Also increases abnormal status resistance by 9 for 10 minutes.",
           "Increases your party's physical defense by 1007 and magic defense by 782. Also increases abnormal status resistance by 10 for 10 minutes."
       ],
       ["Deals 513 physical damage and silences the target for 6 seconds.",
           "Deals 607 physical damage and silences the target for 6 seconds.",
           "Deals 715 physical damage and silences the target for 6 seconds.",
           "Deals 829 physical damage and silences the target for 7 seconds.",
           "Deals 961 physical damage and silences the target for 7 seconds.",
           "Deals 1098 physical damage and silences the target for 7 seconds.",
           "Deals 1242 physical damage and silences the target for 8 seconds.",
           "Deals 1395 physical damage and silences the target for 8 seconds.",
           "Deals 1570 physical damage and silences the target for 8 seconds.",
           "Deals 1755 physical damage and silences the target for 9 seconds.",
           "Deals 1948 physical damage and silences the target for 9 seconds.",
           "Deals 2165 physical damage and silences the target for 9 seconds.",
           "Deals 2406 physical damage and silences the target for 10 seconds.",
           "Deals 2649 physical damage and silences the target for 10 seconds.",
           "Deals 2915 physical damage and silences the target for 10 seconds.",
           "Deals 3208 physical damage and silences the target for 10 seconds."
       ],
       ["Jumps to the selected area and deals 700 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 828 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 976 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 1132 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 1312 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 1500 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 1696 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 1904 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 2144 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 2396 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 2660 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 2956 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 3284 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 3616 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 3980 physical damage to all enemies within 5 meters.",
           "Jumps to the selected area and deals 4380 physical damage to all enemies within 5 meters."
       ],
       ["A fearsome war cry instills Fear within surrounding enemies on a 6m radius for 5 seconds. If the enemy is attacked, there is a 95% chance to dispel the Fear status and reduce their move speed for 6 seconds.",
           "A fearsome war cry instills Fear within surrounding enemies on a 6m radius for 5 seconds. If the enemy is attacked, there is a 90% chance to dispel the Fear status and reduce their move speed for 6 seconds.",
           "A fearsome war cry instills Fear within surrounding enemies on a 6m radius for 5 seconds. If the enemy is attacked, there is a 85% chance to dispel the Fear status and reduce their move speed for 6 seconds.",
           "A fearsome war cry instills Fear within surrounding enemies on a 6m radius for 5 seconds. If the enemy is attacked, there is a 80% chance to dispel the Fear status and reduce their move speed for 6 seconds.",
           "A fearsome war cry instills Fear within surrounding enemies on a 6m radius for 5 seconds. If the enemy is attacked, there is a 75% chance to dispel the Fear status and reduce their move speed for 6 seconds.",
           "A fearsome war cry instills Fear within surrounding enemies on a 6m radius for 5 seconds. If the enemy is attacked, there is a 70% chance to dispel the Fear status and reduce their move speed for 6 seconds.",
           "A fearsome war cry instills Fear within surrounding enemies on a 6m radius for 5 seconds. If the enemy is attacked, there is a 65% chance to dispel the Fear status and reduce their move speed for 6 seconds.",
           "A fearsome war cry instills Fear within surrounding enemies on a 6m radius for 5 seconds. If the enemy is attacked, there is a 60% chance to dispel the Fear status and reduce their move speed for 6 seconds.",
           "A fearsome war cry instills Fear within surrounding enemies on a 6m radius for 5 seconds. If the enemy is attacked, there is a 55% chance to dispel the Fear status and reduce their move speed for 6 seconds.",
           "A fearsome war cry instills Fear within surrounding enemies on a 6m radius for 5 seconds. If the enemy is attacked, there is a 50% chance to dispel the Fear status and reduce their move speed for 6 seconds."
       ],
       ["Your relentless energy decreases the cool-down time of all skills by 2%",
           "Your relentless energy decreases the cool-down time of all skills by 4%",
           "Your relentless energy decreases the cool-down time of all skills by 6%",
           "Your relentless energy decreases the cool-down time of all skills by 8%",
           "Your relentless energy decreases the cool-down time of all skills by 10%",
           "Your relentless energy decreases the cool-down time of all skills by 12%",
           "Your relentless energy decreases the cool-down time of all skills by 14%",
           "Your relentless energy decreases the cool-down time of all skills by 16%",
           "Your relentless energy decreases the cool-down time of all skills by 18%",
           "Your relentless energy decreases the cool-down time of all skills by 20%"
       ],
       ["Channels righteous anger to deal 2342 physical damage to your target and enemies within 6 meters.",
           "Channels righteous anger to deal 2637 physical damage to your target and enemies within 6 meters.",
           "Channels righteous anger to deal 2963 physical damage to your target and enemies within 6 meters.",
           "Channels righteous anger to deal 3328 physical damage to your target and enemies within 6 meters.",
           "Channels righteous anger to deal 3731 physical damage to your target and enemies within 6 meters.",
           "Channels righteous anger to deal 4147 physical damage to your target and enemies within 6 meters.",
           "Channels righteous anger to deal 4608 physical damage to your target and enemies within 6 meters.",
           "Channels righteous anger to deal 5120 physical damage to your target and enemies within 6 meters.",
           "Channels righteous anger to deal 5683 physical damage to your target and enemies within 6 meters.",
           "Channels righteous anger to deal 6310 physical damage to your target and enemies within 6 meters.",
           "Channels righteous anger to deal 7008 physical damage to your target and enemies within 6 meters."
       ],
       ["Viciously charges target within 12 meters dealing 931 physical damage. Decreases move speed by 20 and critical resistance by 5 for 6 seconds.",
           "Viciously charges target within 12 meters dealing 1046 physical damage. Decreases move speed by 22 and critical resistance by 7 for 6 seconds.",
           "Viciously charges target within 12 meters dealing 1178 physical damage. Decreases move speed by 24 and critical resistance by 9 for 6 seconds.",
           "Viciously charges target within 12 meters dealing 1325 physical damage. Decreases move speed by 26 and critical resistance by 11 for 6 seconds.",
           "Viciously charges target within 12 meters dealing 1476 physical damage. Decreases move speed by 28 and critical resistance by 13 for 6 seconds.",
           "Viciously charges target within 12 meters dealing 1639 physical damage. Decreases move speed by 30 and critical resistance by 15 for 6 seconds.",
           "Viciously charges target within 12 meters dealing 1819 physical damage. Decreases move speed by 32 and critical resistance by 17 for 6 seconds.",
           "Viciously charges target within 12 meters dealing 2021 physical damage. Decreases move speed by 34 and critical resistance by 19 for 6 seconds.",
           "Viciously charges target within 12 meters dealing 2244 physical damage. Decreases move speed by 36 and critical resistance by 21 for 6 seconds.",
           "Viciously charges target within 12 meters dealing 2494 physical damage. Decreases move speed by 38 and critical resistance by 25 for 6 seconds."
       ],
       ["Combat awarness decreases damage taken from area attacks by 30% and increases critical attack rate by 1.",
           "Combat awarness decreases damage taken from area attacks by 32% and increases critical attack rate by 2.",
           "Combat awarness decreases damage taken from area attacks by 34% and increases critical attack rate by 3.",
           "Combat awarness decreases damage taken from area attacks by 36% and increases critical attack rate by 4.",
           "Combat awarness decreases damage taken from area attacks by 38% and increases critical attack rate by 5.",
           "Combat awarness decreases damage taken from area attacks by 40% and increases critical attack rate by 6.",
           "Combat awarness decreases damage taken from area attacks by 42% and increases critical attack rate by 7.",
           "Combat awarness decreases damage taken from area attacks by 48% and increases critical attack rate by 8.",
           "Combat awarness decreases damage taken from area attacks by 50% and increases critical attack rate by 9.",
           "Combat awarness decreases damage taken from area attacks by 50% and increases critical attack rate by 10."
       ],
       ["By concentrating on wielding a sword, ignores enemy's Physical DEF by 50% and increases critical damage by 30%. However, the Auto Mana Regen stops and mana is deacreased by 10 per sec. Once all Mana is exhausted, the effects are cancelled.",
           "By concentrating on wielding a sword, ignores enemy's Physical DEF by 52% and increases critical damage by 33%. However, the Auto Mana Regen stops and mana is deacreased by 11 per sec. Once all Mana is exhausted, the effects are cancelled.",
           "By concentrating on wielding a sword, ignores enemy's Physical DEF by 54% and increases critical damage by 36%. However, the Auto Mana Regen stops and mana is deacreased by 12 per sec. Once all Mana is exhausted, the effects are cancelled.",
           "By concentrating on wielding a sword, ignores enemy's Physical DEF by 56% and increases critical damage by 39%. However, the Auto Mana Regen stops and mana is deacreased by 13 per sec. Once all Mana is exhausted, the effects are cancelled.",
           "By concentrating on wielding a sword, ignores enemy's Physical DEF by 58% and increases critical damage by 42%. However, the Auto Mana Regen stops and mana is deacreased by 14 per sec. Once all Mana is exhausted, the effects are cancelled.",
           "By concentrating on wielding a sword, ignores enemy's Physical DEF by 60% and increases critical damage by 45%. However, the Auto Mana Regen stops and mana is deacreased by 15 per sec. Once all Mana is exhausted, the effects are cancelled.",
           "By concentrating on wielding a sword, ignores enemy's Physical DEF by 62% and increases critical damage by 48%. However, the Auto Mana Regen stops and mana is deacreased by 16 per sec. Once all Mana is exhausted, the effects are cancelled.",
           "By concentrating on wielding a sword, ignores enemy's Physical DEF by 64% and increases critical damage by 51%. However, the Auto Mana Regen stops and mana is deacreased by 17 per sec. Once all Mana is exhausted, the effects are cancelled.",
           "By concentrating on wielding a sword, ignores enemy's Physical DEF by 70% and increases critical damage by 55%. However, the Auto Mana Regen stops and mana is deacreased by 18 per sec. Once all Mana is exhausted, the effects are cancelled."
       ],
       ["Inflicts 780 physical damage and adds extra damage equivalent to 9% of user's current HP.",
           "Inflicts 875 physical damage and adds extra damage equivalent to 10% of user's current HP.",
           "Inflicts 972 physical damage and adds extra damage equivalent to 11% of user's current HP.",
           "Inflicts 1080 physical damage and adds extra damage equivalent to 12% of user's current HP.",
           "Inflicts 1200 physical damage and adds extra damage equivalent to 13% of user's current HP.",
           "Inflicts 1332 physical damage and adds extra damage equivalent to 14% of user's current HP.",
           "Inflicts 1479 physical damage and adds extra damage equivalent to 15% of user's current HP.",
           "Inflicts 1643 physical damage and adds extra damage equivalent to 16% of user's current HP."
       ],
       ["By crying for freedom, this lifts all cancelable debuffs on the user and party members while increasing abnormal states RES by 40 and Movement Speed by 15 for 10 seconds. The user becomes immune to abnormal states for 10 seconds.",
           "By crying for freedom, this lifts all cancelable debuffs on the user and party members while increasing abnormal states RES by 42 and Movement Speed by 17 for 10 seconds. The user becomes immune to abnormal states for 12 seconds.",
           "By crying for freedom, this lifts all cancelable debuffs on the user and party members while increasing abnormal states RES by 44 and Movement Speed by 19 for 10 seconds. The user becomes immune to abnormal states for 14 seconds.",
           "By crying for freedom, this lifts all cancelable debuffs on the user and party members while increasing abnormal states RES by 46 and Movement Speed by 21 for 10 seconds. The user becomes immune to abnormal states for 16 seconds.",
           "By crying for freedom, this lifts all cancelable debuffs on the user and party members while increasing abnormal states RES by 48 and Movement Speed by 23 for 10 seconds. The user becomes immune to abnormal states for 18 seconds.",
           "By crying for freedom, this lifts all cancelable debuffs on the user and party members while increasing abnormal states RES by 50 and Movement Speed by 25 for 10 seconds. The user becomes immune to abnormal states for 20 seconds.",
           "By crying for freedom, this lifts all cancelable debuffs on the user and party members while increasing abnormal states RES by 52 and Movement Speed by 27 for 10 seconds. The user becomes immune to abnormal states for 22 seconds."
       ],
       ["Recovers HP and MP equivalent to 50% and 25% of damage done to enemies by party members for 40 secs.",
           "Recovers HP and MP equivalent to 60% and 30% of damage done to enemies by party members for 40 secs.",
           "Recovers HP and MP equivalent to 70% and 35% of damage done to enemies by party members for 40 secs.",
           "Recovers HP and MP equivalent to 80% and 40% of damage done to enemies by party members for 40 secs.",
           "Recovers HP and MP equivalent to 90% and 45% of damage done to enemies by party members for 40 secs.",
           "Recovers HP and MP equivalent to 100% and 50% of damage done to enemies by party members for 40 secs."
       ],
       ["Increases Physical ATK by 140, skill ATK by 683, and Critical rate by 20. This skill consumes 170% of HP instead of MP.",
           "Increases Physical ATK by 152, skill ATK by 739, and Critical rate by 21. This skill consumes 170% of HP instead of MP.",
           "Increases Physical ATK by 164, skill ATK by 814, and Critical rate by 22. This skill consumes 170% of HP instead of MP.",
           "Increases Physical ATK by 176, skill ATK by 898 and Critical rate by 23. This skill consumes 170% of HP instead of MP.",
           "Increases Physical ATK by 188, skill ATK by 991 and Critical rate by 24. This skill consumes 170% of HP instead of MP.",
           "Increases Physical ATK by 200, skill ATK by 1095 and Critical rate by 25. This skill consumes 170% of HP instead of MP."
       ],
       ["Deals 1516 physical damage to target and enemies and knocks them back.",
           "Deals 1684 physical damage to target and enemies and knocks them back.",
           "Deals 1870 physical damage to target and enemies and knocks them back.",
           "Deals 2078 physical damage to target and enemies and knocks them back.",
           "Deals 2190 physical damage to target and enemies and knocks them back."
       ],
       ["Brandish your sword to deal 2054 physical damage on enemies within range and cause bleeding for 5 sec. Bleeding enemies regenration rates decrease by 85%.",
           "Brandish your sword to deal 2281 physical damage on enemies within range and cause bleeding for 5 sec. Bleeding enemies regenration rates decrease by 90%.",
           "Brandish your sword to deal 2535 physical damage on enemies within range and cause bleeding for 5 sec. Bleeding enemies regenration rates decrease by 95%.",
           "Brandish your sword to deal 2672 physical damage on enemies within range and cause bleeding for 5 sec. Bleeding enemies regenration rates decrease by 99%."
       ],
       ["With outburst of bloody rage, inflicts 947 physical damage on enemies within 6m and adds extra damage depending on the user's lost HP. Once Last Stand is activated, damage and regen are highly decreased for 6 seconds.",
           "With outburst of bloody rage, inflicts 1051 physical damage on enemies within 6m and adds extra damage depending on the user's lost HP. Once Last Stand is activated, damage and regen are highly decreased for 6 seconds."
       ]
   ],
   cd: [
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [20, 20, 19, 19, 18, 18, 17, 17, 16, 14],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [30, 29, 28, 27, 26, 25, 24, 23, 22, 20],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [60, 60, 60, 60, 60, 60, 60, 60, 60, 60],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90],
       [60, 58, 56, 54, 52, 50, 48, 46, 44, 40],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120],
       [40, 39, 38, 37, 36, 35, 34, 33, 32, 20],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [6, 6, 6, 6, 6, 6, 6, 6, 6],
       [16, 16, 16, 16, 16, 16, 16, 16],
       [90, 90, 90, 90, 90, 90, 90],
       [120, 120, 120, 120, 120, 120],
       [6, 6, 6, 6, 6, 6],
       [28, 28, 28, 28, 28],
       [36, 36, 36, 36],
       [120, 120]
   ],
   mp: [
       [16, 19, 26, 33, 41, 50, 61, 74, 90, 109, 132, 156, 184, 213, 247, 284],
       [30, 41, 51, 63, 79, 95, 115, 139, 169, 203],
       [30, 38, 48, 60, 73, 89, 108, 131, 158, 188, 221, 260, 301, 348, 396, 445],
       [18, 23, 28, 34, 41, 49, 59, 71, 83, 97, 113, 129, 148, 166, 185, 206],
       [76, 94, 112, 135, 162, 194, 231, 270, 316, 363, 416, 473],
       [79, 99, 122, 147, 178, 216, 262, 312, 369, 435, 504, 583, 665, 747, 841, 946],
       [54, 66, 78, 94, 113, 136, 160, 187, 218, 250, 287, 324, 360, 401, 446, 492],
       [84, 103, 124, 150, 182, 220, 260, 307, 358, 413],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [117, 141, 170, 203, 240, 281, 327, 375, 431, 486, 540, 602, 669, 738, 810, 890],
       [139, 167, 203, 246, 290, 343, 399, 462, 536, 603, 677, 761, 853, 948, 1053, 1170],
       [103, 125, 151, 178, 209, 243, 281, 323, 364, 409],
       [118, 141, 166, 194, 226, 259, 297, 333, 370, 412],
       [108, 130, 157, 191, 231, 276, 325, 384, 444, 514, 586, 660, 743, 835, 930, 1032],
       [212, 250, 292, 339, 388, 445, 499, 555, 617, 687, 755, 830, 911, 1001, 1100, 1208],
       [267, 316, 372, 431, 500, 571, 646, 725, 816, 913, 1013, 1126, 1251, 1377, 1515, 1668],
       [357, 422, 497, 577, 668, 765, 865, 970, 1092, 1221, 1355, 1507, 1673, 1842, 2028, 2232],
       [351, 402, 455, 512, 570, 634, 703, 773, 850, 933],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1066, 1200, 1348, 1514, 1698, 1887, 2097, 2330, 2586, 2871, 3189],
       [424, 476, 536, 603, 672, 746, 828, 920, 1021, 1135],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [802, 892, 983, 1080, 1187, 1304, 1432, 1572, 1648],
       [406, 455, 505, 562, 624, 693, 769, 854],
       [704, 773, 850, 933, 1025, 1125, 1236],
       [773, 850, 933, 1025, 1125, 1236],
       [1080, 1187, 1304, 1432, 1572, 1648],
       [1560, 1733, 1924, 2138, 2253],
       [1445, 1604, 1783, 1879],
       [2995, 3307]
   ],
   cast: [
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0]
   ],
   skillLevel: [
       [1, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60],
       [4, 8, 12, 16, 20, 24, 28, 32, 36, 40],
       [6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66],
       [8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68],
       [10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58],
       [12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72],
       [17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77],
       [19, 23, 27, 31, 35, 39, 43, 47, 51, 55],
       [21, 25, 29, 33, 37, 41, 45, 49, 53, 57],
       [23, 27, 31, 35, 39, 43, 47, 51, 55, 59],
       [25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77, 81, 85],
       [27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67, 71, 75, 79, 83, 87],
       [32, 36, 40, 44, 48, 52, 56, 60, 64, 68],
       [34, 38, 42, 46, 50, 54, 58, 62, 66, 70],
       [36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96],
       [38, 42, 46, 50, 54, 58, 62, 66, 70, 74, 78, 82, 86, 90, 94, 98],
       [40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 99],
       [40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 99],
       [51, 55, 59, 63, 67, 71, 75, 79, 83, 87],
       [55, 59, 63, 67, 71, 75, 79, 83, 87, 91],
       [59, 63, 67, 71, 75, 79, 83, 87, 91, 95, 99],
       [61, 65, 69, 73, 77, 81, 85, 89, 93, 97],
       [65, 69, 73, 77, 81, 85, 89, 93, 97, 99],
       [69, 73, 77, 81, 85, 89, 93, 97, 99],
       [71, 75, 79, 83, 87, 91, 95, 99],
       [75, 79, 83, 87, 91, 95, 99],
       [79, 83, 87, 91, 95, 99],
       [81, 85, 89, 93, 97, 99],
       [85, 89, 93, 97, 99],
       [89, 93, 97, 99],
       [95, 99]
   ]

};